"""The checkouts: the repository working trees a scenario's person works in, made real.

A scenario states what a person's checkouts hold only through the records that read them: the
files an observation reads from the working tree (path, size, git state, digest), the members a
repository-authored source's revision names (path, size, digest), and those of a source whose home
the scenario does not state at a path an observation reads from the tree, the branch, commit and
remote a repository binding observed, and the checkout a source selection names. Before the first
step this builds those git checkouts, and every stated value that stands for something only a real
checkout has is replaced by it wherever a field of its kind holds it, as the signing feature
replaces a public key:

  the checkout path a selection names  the directory built for it
  a file digest a record states        the sha256 of the bytes written at that path
  the commit a binding observed        the HEAD of the checkout it was made in, or the commit a
                                       file edit of a branch's ref names
  a path a preparation observed        the directory built for it, or the first checkout, where
                                       the code works with no repository bound from it

Which checkout a record speaks of:

  - a selection names its checkout by path, and each path is one checkout;
  - an observation reads the checkout its selection names;
  - a repository binding was made in the checkout its observed working bytes were read from, else
    in the one checkout the selections read its repository in; a repository no selection reads is
    a checkout of its own;
  - a repository-authored home speaks of the checkout its binding was made in, and a source's
    manifest of the checkout the binding its first stated home rests on was made in.

Everything else speaks of the first checkout: the one a record names at the earliest step. A step
works in the checkout a record it returns speaks of, else one it carries, else the one checkout of
the repository that owns its request or that a record it carries works in (`work_scope`), and
the code under test answers it there; any other step runs in the first checkout, as a person runs
the product inside their repository.

A file whose digest names a member of the scenario holds that member's bytes; a file whose digest
the owner mints, or states, holds generated bytes of its stated size, the same bytes for the same
stated content. A file is committed unless an observation reads it `modified`, when HEAD holds
other bytes, or `untracked`, when it is not added. A checkout's branch and remote are the ones its
bindings observed before any edit switched its branch, `main` when none says. A checkout a binding
says is a `worktree` is added as a git worktree of the first checkout built of its repository, and
holds only what its records state. Checkouts whose bindings state one commit before any switch
share it: the later one is a clone of the earlier (a worktree is added at its repository's HEAD),
its committed files are the commit's, and only its modified and untracked files are its own. A
file edit writing a 40-hex commit into `.git/refs/heads/...` names a branch the person switches
to: the driver makes that commit, its tree HEAD's without the files the edits before the same
step remove, and writes it in the stated commit's place; once the edits before a step have
rewritten `.git/HEAD`, the index is the new HEAD's, as switching branches leaves it.

The first state is what records state before anything changes a path: a record is dated by the
first step that sends, carries or returns it, or a record naming it by digest, and a fact about a
path a file edit changed by then is the edit's, not the first state's. A digest the owner mints for
a file it reads is known before the step that returns or carries it: the digest of the bytes at
that path then, which the answer must state. A manifest member whose size the owner mints names a
file the code under test writes, and so does another record's read of a file by that same minted
size, such as a later observation of it: it is not in the first state, and after a step that code
in scope answers, each such file a record it returns states must be the file at its path then, by
digest and size.

What this cannot build is `blocked` by name: a selection naming more than one checkout, a binding
whose repository the selections read in several checkouts with no observation saying which, a
record of a scenario with several checkouts that says of none which it speaks of, one path of a
checkout stated with two contents in the first state, two remotes for one checkout, two branches
or two commits for one before any edit switches it, and a checkout sharing a commit whose files
it states otherwise than the commit holds them. A path another record names
that no selection does, such as a capture claiming input from another repository, is left as
stated.
"""
from __future__ import annotations

import hashlib
import os
import pathlib
import re
import subprocess

import cases
import executor

OBSERVATION = "source_observation"
MANIFEST = "source_manifest"
HOME = "source_home"
BINDING = "repository_binding"
AUTHORED = "repository_authored"
PATH_KEY = "checkout"
SELECTION = "source_selection"
PREPARATION = "preparation"
REQUEST = "operation_request"
WORKTREE = "worktree"
NEVER = float("inf")
BRANCH = "main"
HEAD = ".git/HEAD"
REFS = ".git/refs/heads/"
COMMIT = re.compile(r"[0-9a-f]{40}")
IDENTITY = {"GIT_AUTHOR_NAME": "agent-bios conformance", "GIT_AUTHOR_EMAIL": "driver@localhost",
            "GIT_COMMITTER_NAME": "agent-bios conformance",
            "GIT_COMMITTER_EMAIL": "driver@localhost",
            "GIT_AUTHOR_DATE": "2026-01-01T00:00:00Z", "GIT_COMMITTER_DATE": "2026-01-01T00:00:00Z"}


def install(run) -> None:
    run.prepare_hooks.append(build)
    run.before_hooks.append(known_files)
    run.before_hooks.append(switched_index)
    run.message_hooks.append(working_in)
    run.after_hooks.append(written_files)


def blocked(why: str):
    return executor.Stop(executor.BLOCKED, why)


def named_checkouts(templates: dict) -> set[str]:
    """The checkout paths the scenario's source selections name."""
    found: set[str] = set()
    for record in templates.values():
        found |= selected(record)
    return found


def selected(record: dict) -> set[str]:
    """The checkout paths a source selection's roots name."""
    found: set[str] = set()
    for root in record.get("roots", []) if record.get("kind") == SELECTION else []:
        place = root.get("place") if isinstance(root, dict) else None
        if isinstance(place, dict) and isinstance(place.get(PATH_KEY), str):
            found.add(place[PATH_KEY])
    return found


def joined(run, record: str, pointer: str) -> str | None:
    """The record whose digest the record states at the pointer, if a join says so."""
    return next((join["digest_of"] for join in run.joins.get(record, [])
                 if join["pointer"] == pointer and "digest_of" in join), None)


def dated(run) -> dict[str, float]:
    """Each record's first step: the first that sends, carries or returns it, or that uses a
    record naming it by digest."""
    first: dict[str, float] = {}
    for index, step in enumerate(run.built["steps"]):
        result = step.get("result")
        for name in [step.get("request"), *step.get("carries", []), *step.get("returns", []),
                     result, run.receipt_of_result(result) if result else None]:
            if name and name not in first:
                first[name] = index
    changed = True
    while changed:
        changed = False
        for join in run.built["joins"]:
            named, by = join.get("digest_of"), join["record"]
            if named and by in first and first[by] < first.get(named, NEVER):
                first[named] = first[by]
                changed = True
    return first


class Plan:
    """Which checkout each record speaks of, by key: the path a selection names, or
    `repository <id>` for a repository no selection reads; and the keys, the first checkout
    first."""

    def __init__(self, run):
        self.of: dict[str, str] = {}
        self.repository: dict[str, str] = {}
        self.paths: set[str] = set()
        read_in: dict[str, set[str]] = {}
        for name, record in run.templates.items():
            paths = selected(record)
            if len(paths) > 1:
                raise blocked(f"the selection {name} names {len(paths)} checkouts "
                              f"({', '.join(sorted(paths))}), and a selection reading more than "
                              "one is not built yet")
            if not paths:
                continue
            key = self.of[name] = paths.pop()
            self.paths.add(key)
            for root in record["roots"]:
                if isinstance(root.get("place", {}).get("repository_id"), str):
                    read_in.setdefault(root["place"]["repository_id"], set()).add(key)
                    self.repository.setdefault(key, root["place"]["repository_id"])
        for name, record in run.templates.items():
            if record.get("kind") == OBSERVATION and \
                    joined(run, name, "/selection_digest") in self.of:
                self.of[name] = self.of[joined(run, name, "/selection_digest")]
        for name, record in run.templates.items():
            if record.get("kind") != BINDING or not isinstance(record.get("observed"), dict):
                continue
            observation = joined(run, name, "/observed/working_bytes_digest")
            repository = record.get("repository_id")
            places = read_in.get(repository, set())
            if observation in self.of:
                self.of[name] = self.of[observation]
            elif len(places) == 1:
                self.of[name] = next(iter(places))
            elif not places:
                self.of[name] = f"repository {repository}"
            else:
                raise blocked(f"the binding {name} binds {repository}, which the selections read "
                              f"in {len(places)} checkouts, and names no observation saying "
                              "which it was made in")
            self.repository.setdefault(self.of[name], repository)
        first = dated(run)
        self.homes = homes(run, first)
        for name, record in run.templates.items():
            binding = joined(run, name, "/home/binding_evidence_digest") \
                if record.get("kind") == HOME else self.homes.get(record.get("source_id")) \
                if record.get("kind") == MANIFEST else None
            if binding in self.of:
                self.of[name] = self.of[binding]
        when: dict[str, float] = {}
        for name, key in self.of.items():
            when[key] = min(when.get(key, NEVER), first.get(name, NEVER))
        self.keys: list[str | None] = sorted(when, key=lambda key: (when[key], key)) or [None]
        # Each request a repository owns, and each record working in a repository, where that
        # repository is read in one checkout.
        self.scoped: dict[str, str] = {}
        for name, record in run.templates.items():
            scope = record.get("owner") if record.get("kind") == REQUEST else \
                record.get("work_scope")
            if isinstance(scope, dict) and scope.get("layer") == "repository":
                places = [key for key, repository in self.repository.items()
                          if repository == scope.get("repository_id")]
                if len(places) == 1:
                    self.scoped[name] = places[0]

    def default(self) -> str | None:
        return self.keys[0]

    def single(self) -> bool:
        return len(self.keys) == 1

    def record_key(self, name: str, what: str) -> str | None:
        """The checkout a record speaks of; with several checkouts, one it does not say is
        blocked."""
        if name in self.of:
            return self.of[name]
        if self.single():
            return self.default()
        raise blocked(f"{what} {name} says of none of the scenario's {len(self.keys)} checkouts "
                      "which it speaks of")

    def step_key(self, step: dict) -> str | None:
        """The checkout a step works in: the one a record it returns speaks of, else one it
        carries, else the one checkout of the repository that owns its request or that a record
        it carries works in; None for any other step."""
        for name in step.get("returns", []):
            if name in self.of:
                return self.of[name]
        for name in step.get("carries", []):
            if name in self.of:
                return self.of[name]
        for name in [step.get("request"), *step.get("carries", [])]:
            if name in self.scoped:
                return self.scoped[name]
        return None


def homes(run, first: dict[str, float]) -> dict[str, str]:
    """Each repository-authored source, and the binding its first stated home rests on: the home
    record the earliest step uses, by name among those no step uses."""
    found: dict[str, tuple[float, str, str]] = {}
    for name, record in run.templates.items():
        if record.get("kind") != HOME or record.get("home", {}).get("mode") != AUTHORED:
            continue
        binding = joined(run, name, "/home/binding_evidence_digest")
        if binding is None:
            continue
        held, source = (first.get(name, NEVER), name, binding), record.get("source_id")
        if source not in found or held < found[source]:
            found[source] = held
    return {source: binding for source, (_, _, binding) in found.items()}


def edits_of(run, plan: Plan) -> dict[tuple, list[int]]:
    """Each (checkout, path) a file edit changes, and the steps it comes before."""
    index = {step["name"]: i for i, step in enumerate(run.built["steps"])}
    steps = {step["name"]: step for step in run.built["steps"]}
    found: dict[tuple, list[int]] = {}
    for event in run.built.get("world", {}).get("events", []):
        if event["kind"] == "file_edit":
            key = plan.step_key(steps[event["before"]])
            key = plan.default() if key is None else key
            found.setdefault((key, event["path"]), []).append(index[event["before"]])
    return found


def places(run, name: str, record: dict) -> list[tuple[str, dict]]:
    """(pointer, entry) for each file a record states: an observation's tree reads, the members
    of a repository-authored source's manifest, and those of each manifest of a source an
    admission authors into a repository."""
    if record.get("kind") == OBSERVATION:
        return [(f"/read/{i}", read) for i, read in enumerate(record.get("read", []))
                if read.get("read") == "tree"]
    if record.get("kind") != MANIFEST:
        return []
    source = record.get("source_id")
    if source in authored(run) or source in admitted_sources(run) or name in admitted(run):
        return [(f"/members/{i}", member) for i, member in enumerate(record.get("members", []))]
    if source not in homed(run):
        tree = tree_paths(run)
        return [(f"/members/{i}", member) for i, member in enumerate(record.get("members", []))
                if member.get("path") in tree]
    return []


def place_key(run, plan: Plan, name: str, record: dict) -> str | None:
    """The checkout whose files a record states: an observation's own, and a manifest's source's
    home's."""
    if record.get("kind") == MANIFEST and record.get("source_id") in plan.homes:
        binding = plan.homes[record["source_id"]]
        if binding in plan.of:
            return plan.of[binding]
    return plan.record_key(name, "the record")


def homed(run) -> set:
    """The sources whose home the scenario states."""
    return {record.get("source_id") for record in run.templates.values()
            if record.get("kind") == HOME}


def tree_paths(run) -> set[str]:
    return {read["path"] for record in run.templates.values()
            if record.get("kind") == OBSERVATION
            for read in record.get("read", []) if read.get("read") == "tree"}


def authored(run) -> set:
    """The sources a home record states as repository-authored, whatever else is proposed."""
    return {record.get("source_id") for record in run.templates.values()
            if record.get("kind") == HOME and record.get("home", {}).get("mode") == AUTHORED}


def admitted(run) -> set[str]:
    """The manifests an admission into a repository-authored destination carries."""
    return set().union(*cases.admitted_into_a_repository(run.built).values())


def admitted_sources(run) -> set[str]:
    """The sources an admission authors into a repository-authored destination: every revision
    of one, a later publication's too, names files of the checkout."""
    return set(cases.admitted_into_a_repository(run.built))


def written(run, plan: Plan) -> dict[str, dict[str, tuple[str | None, str]]]:
    """Each file a record states that the code under test writes, by record: pointer ->
    (checkout, path). A manifest member whose size is minted is one, since no one knows the file
    before the code writes it, and so is another record's read of a file by that same minted
    size."""
    sized = {(join["record"], join["pointer"]): join["minted"] for join in run.built["joins"]
             if "minted" in join}
    found: dict[str, dict[str, tuple[str | None, str]]] = {}
    published: set[str] = set()
    for manifests in (True, False):
        for name, record in run.templates.items():
            if (record.get("kind") == MANIFEST) != manifests:
                continue
            for pointer, entry in places(run, name, record):
                size = sized.get((name, pointer + "/size"))
                if size is None or not (manifests or size in published):
                    continue
                published.add(size)
                found.setdefault(name, {})[pointer] = (place_key(run, plan, name, record),
                                                       entry["path"])
    return found


def written_files(run, step: dict, answer: dict, how: str) -> None:
    """After a step code in scope answered, each file it says it wrote is the one at its path."""
    if run.checkout is None or how == "given":
        return
    for index, name in enumerate(step.get("returns", [])):
        record = answer.get("returned", [])[index]
        for pointer, (checkout, path) in run.written.get(name, {}).items():
            member = executor.at(record, pointer)[1]
            target = checkout / path
            data = target.read_bytes() if target.is_file() else None
            if data is None or not isinstance(member, dict) \
                    or member.get("digest") != hashlib.sha256(data).hexdigest() \
                    or member.get("size") != len(data):
                held = "no file" if data is None else \
                    f"{len(data)} bytes hashing to {hashlib.sha256(data).hexdigest()}"
                raise executor.Stop(executor.FAILED, f"{name}{pointer} says the code wrote {path} "
                                                     f"as {executor.shown(member)}, and the "
                                                     f"checkout holds {held} there",
                                    step=step["name"], record=name, pointer=pointer)


def file_digests(run, plan: Plan, writes: dict) -> dict[str, tuple[str, str | None, str]]:
    """Each minted name that is the digest of a file the owner reads: (record, checkout, path)."""
    found = {}
    for join in run.built["joins"]:
        if "minted" not in join or not join["pointer"].endswith("/digest"):
            continue
        record = join["record"]
        template = run.templates[record]
        for pointer, entry in places(run, record, template):
            if pointer in writes.get(record, {}):
                continue
            if join["pointer"] == pointer + "/digest":
                found.setdefault(join["minted"], (record, place_key(run, plan, record, template),
                                                  entry["path"]))
    return found


def known_files(run, step: dict) -> None:
    """Before a step, the digest of each file a record it carries or returns reads."""
    if run.checkout is None:
        return
    names = {step.get("request"), *step.get("carries", []), *step.get("returns", [])}
    learned = False
    for minted, (record, checkout, path) in run.file_digests.items():
        target = checkout / path
        if record in names and minted not in run.learned and target.is_file():
            run.learned[minted] = hashlib.sha256(target.read_bytes()).hexdigest()
            learned = True
    if learned:
        run.forget()


def switched_index(run, step: dict) -> None:
    """Once the edits before a step have rewritten a checkout's `.git/HEAD`, its index is the
    new HEAD's tree, as switching branches leaves it: a file the new branch lacks is no longer
    staged, and a file the person changed stays changed in the working tree."""
    for checkout, home in run.switched.get(step["name"], []):
        git(checkout, home, "read-tree", "HEAD")


def working_in(run, step: dict, message: dict) -> None:
    """The step is answered in the checkout it works in, where that is not the first."""
    checkout = run.worked_in.get(step["name"])
    if checkout is not None and checkout != run.cwd:
        message["cwd"] = str(checkout)


def facts(run, plan: Plan) -> dict[tuple, dict]:
    """(checkout, path) -> {"size", "state", "key", "bytes"?, "literal"?} of the first state.

    `key` says which content the file holds: a member's name, a minted value, or a literal
    digest. A fact dated after a file edit of its path is the edit's."""
    first = dated(run)
    writes = written(run, plan)
    changes = edits_of(run, plan)
    joins = {(join["record"], join["pointer"]): join for join in run.built["joins"]}
    found: dict[tuple, dict] = {}

    def content(record: str, pointer: str, size: int, state: str | None) -> dict:
        join = joins.get((record, pointer))
        digest = executor.at(run.templates[record], pointer)[1]
        if join is not None and join.get("digest_of") in run.members:
            new = {"key": ("member", join["digest_of"]), "bytes": run.members[join["digest_of"]]}
        elif join is not None:
            new = {"key": ("minted", join.get("minted") or join.get("digest_of"))}
        else:
            new = {"key": ("literal", digest), "literal": digest}
        new.update(size=size, state=state)
        return new

    for name, record in run.templates.items():
        when = first.get(name, NEVER)
        stated = places(run, name, record)
        if not stated:
            continue
        key = place_key(run, plan, name, record)
        for pointer, entry in stated:
            path = entry["path"]
            if pointer in writes.get(name, {}):
                continue
            if any(before <= when for before in changes.get((key, path), [])):
                continue
            new = content(name, pointer + "/digest", entry["size"], entry.get("state"))
            held = found.get((key, path))
            if held is None:
                found[(key, path)] = new
                continue
            if (held["key"], held["size"]) != (new["key"], new["size"]):
                raise blocked(f"the scenario states two contents for {path} in "
                              f"{shown(key)}'s first state, and a checkout that changes between "
                              "steps without an edit is not built yet")
            held["state"] = held["state"] or new["state"]
    return found


def shown(key: str | None) -> str:
    return "its checkout" if key is None else key


def made(key: tuple, size: int, variant: str = "") -> bytes:
    """Bytes of the stated size standing for one stated content."""
    seed = f"{variant}{key[0]} {key[1]}\n".encode()
    body = seed * (size // len(seed) + 1)
    return body[:size]


def git(checkout: pathlib.Path, home: pathlib.Path, *arguments: str,
        index: pathlib.Path | None = None) -> str:
    env = {key: value for key, value in os.environ.items() if not key.startswith("GIT_")}
    env.update(IDENTITY, HOME=str(home), GIT_CONFIG_NOSYSTEM="1")
    if index is not None:
        env["GIT_INDEX_FILE"] = str(index)
    try:
        done = subprocess.run(["git", "-c", "commit.gpgsign=false",
                               "-c", "core.hooksPath=/dev/null", *arguments], cwd=checkout,
                              env=env, capture_output=True, text=True, timeout=60)
    except FileNotFoundError as error:
        raise blocked("git is not on PATH, so the driver cannot build the checkout") from error
    if done.returncode != 0:
        raise blocked(f"git {arguments[0]} exited {done.returncode}: {done.stderr.strip()}")
    return done.stdout.strip()


class Seen:
    """What a checkout's bindings observed: its remote, its branch before any edit switched it,
    whether one says it is a worktree, and the commits they state, with the step each is dated
    by."""

    def __init__(self):
        self.remotes: set[str] = set()
        self.branches: set[str] = set()
        self.worktree = False
        self.commits: list[tuple[str, float]] = []
        self.initial: set[str] = set()


def observed(run, plan: Plan, changes: dict) -> dict[str | None, Seen]:
    """What each checkout's bindings observed."""
    first = dated(run)
    joins = {(join["record"], join["pointer"]) for join in run.built["joins"]}
    found = {key: Seen() for key in plan.keys}
    for name, record in run.templates.items():
        seen = record.get("observed") if record.get("kind") == BINDING else None
        if not isinstance(seen, dict):
            continue
        key = plan.record_key(name, "the binding")
        held, when = found[key], first.get(name, NEVER)
        switched = any(before <= when for before in changes.get((key, HEAD), []))
        if seen.get("branch") and not switched:
            held.branches.add(seen["branch"])
        if seen.get("locator"):
            held.remotes.add(seen["locator"])
        if seen.get("commit") and (name, "/observed/commit") not in joins:
            held.commits.append((seen["commit"], when))
            if not switched:
                held.initial.add(seen["commit"])
        held.worktree = held.worktree or record.get("relation", {}).get("how") == WORKTREE
    for key, held in found.items():
        if len(held.remotes) > 1:
            raise blocked(f"the scenario's bindings observe {len(held.remotes)} remotes for "
                          f"{shown(key)}, and one checkout has one origin")
        if len(held.branches) > 1:
            raise blocked(f"the scenario's bindings observe {len(held.branches)} branches for "
                          f"{shown(key)} before any edit switches it, and a checkout that changes "
                          "branch between steps without an edit is not built yet")
        if len(held.initial) > 1:
            raise blocked(f"the scenario's bindings observe {len(held.initial)} commits for "
                          f"{shown(key)} before any edit switches it, and a checkout that commits "
                          "between steps without an edit is not built yet")
    return found


def build(run) -> None:
    plan = Plan(run)
    stated = facts(run, plan)
    changes = edits_of(run, plan)
    seen = observed(run, plan, changes)
    home = (run.workdir / "git-home").resolve()
    home.mkdir(parents=True)
    built: dict[str | None, pathlib.Path] = {}
    replaced: dict[tuple[str, str], str] = {}
    order = [key for key in plan.keys if not seen[key].worktree] + \
        [key for key in plan.keys if seen[key].worktree]
    for key in order:
        checkout = (run.workdir / ("checkout" if key == plan.default()
                                   else f"checkout-{plan.keys.index(key)}")).resolve()
        main = next((built[other] for other in built if seen[key].worktree
                     and plan.repository.get(other) == plan.repository.get(key)), None)
        base = next((built[other] for other in built
                     if seen[key].initial & seen[other].initial), None)
        if main is not None and base is not None and base != main:
            raise blocked(f"the worktree {shown(key)} states the commit of a checkout other than "
                          "its repository's first, and such a worktree is not built yet")
        replaced.update(made_in(checkout, home, main, base, seen[key], {
            path: fact for (where, path), fact in stated.items() if where == key}))
        built[key] = checkout
    for key, checkout in built.items():
        if key in plan.paths:
            replaced[("path", key)] = str(checkout)
    for place in worked_in(run.templates):
        replaced[("locator", place)] = str(built.get(place, built[plan.default()]))
    run.commits = switches(run, plan, built, home)
    run.switched = {}
    steps = {step["name"]: step for step in run.built["steps"]}
    for event in run.built.get("world", {}).get("events", []):
        if event["kind"] == "file_edit" and event["path"] == HEAD:
            key = plan.step_key(steps[event["before"]])
            place = (built[plan.default() if key is None else key], home)
            if place not in run.switched.setdefault(event["before"], []):
                run.switched[event["before"]].append(place)
    for key, checkout in built.items():
        head = git(checkout, home, "rev-parse", "HEAD")
        for commit, _ in seen[key].commits:
            real = run.commits.get(commit, head)
            if replaced.get(("commit", commit), real) != real:
                raise blocked(f"the scenario states the commit {commit} for two checkouts, or for "
                              "two commits of one")
            replaced[("commit", commit)] = real
    for name, record in run.templates.items():
        run.templates[name] = swapped(record, replaced)
    run.checkout = run.cwd = built[plan.default()]
    steps = {step["name"]: plan.step_key(step) for step in run.built["steps"]}
    run.worked_in = {name: built[key] for name, key in steps.items() if key is not None}
    writes = written(run, plan)
    run.written = {name: {pointer: (built[key], path) for pointer, (key, path) in members.items()}
                   for name, members in writes.items()}
    run.file_digests = {minted: (record, built[key], path) for minted, (record, key, path)
                        in file_digests(run, plan, writes).items()}
    run.forget()


def made_in(checkout: pathlib.Path, home: pathlib.Path, main: pathlib.Path | None,
            base: pathlib.Path | None, seen: Seen,
            stated: dict[str, dict]) -> dict[tuple[str, str], str]:
    """One checkout holding what its records state: committed on its branch, then modified and
    untracked files written; a worktree added to the checkout of its repository built first; and
    a checkout sharing the commit of one built before it made from that commit (`sharing`). And
    each literal digest stated, replaced by the digest of the bytes written for it."""
    branch = next(iter(seen.branches), BRANCH)
    remote = next(iter(seen.remotes), None)
    if main is not None:
        origin = git(main, home, "config", "--get", "remote.origin.url") \
            if "origin" in git(main, home, "remote").split() else None
        if remote != origin:
            raise blocked(f"the worktree at {checkout} observes the remote {remote} where its "
                          f"repository's checkout has {origin}, and a worktree shares its origin")
        if base is not None:
            git(main, home, "worktree", "add", "-q", "-b", branch, str(checkout), "HEAD")
            return sharing(checkout, home, stated)
        git(main, home, "worktree", "add", "-q", "--no-checkout", "-b", branch, str(checkout))
    elif base is not None:
        git(base, home, "clone", "-q", "--no-hardlinks", str(base), str(checkout))
        if git(checkout, home, "symbolic-ref", "-q", "--short", "HEAD") != branch:
            git(checkout, home, "checkout", "-q", "-b", branch)
        if remote:
            git(checkout, home, "remote", "set-url", "origin", remote)
        else:
            git(checkout, home, "remote", "remove", "origin")
        return sharing(checkout, home, stated)
    else:
        checkout.mkdir(parents=True)
        git(checkout, home, "init", "-q", "-b", branch)
    later, replaced = [], {}
    for path, fact in sorted(stated.items()):
        data = fact.get("bytes") or made(fact["key"], fact["size"])
        if fact.get("literal"):
            replaced[("digest", fact["literal"])] = hashlib.sha256(data).hexdigest()
        target = checkout / path
        target.parent.mkdir(parents=True, exist_ok=True)
        if fact["state"] == "untracked":
            later.append((target, data))
            continue
        if fact["state"] == "modified":
            later.append((target, data))
            data = made(fact["key"], fact["size"], "committed before ")
        target.write_bytes(data)
    git(checkout, home, "add", "-A")
    git(checkout, home, "commit", "-q", "--allow-empty", "--no-verify", "-m",
        "the checkout as the scenario states it")
    for target, data in later:
        target.write_bytes(data)
    if remote and main is None:
        git(checkout, home, "remote", "add", "origin", remote)
    return replaced


def blob(checkout: pathlib.Path, home: pathlib.Path, path: str) -> bytes | None:
    """The bytes HEAD holds at the path, or None where it holds no file there."""
    env = {key: value for key, value in os.environ.items() if not key.startswith("GIT_")}
    env.update(HOME=str(home), GIT_CONFIG_NOSYSTEM="1")
    done = subprocess.run(["git", "cat-file", "blob", f"HEAD:{path}"], cwd=checkout, env=env,
                          capture_output=True, timeout=60)
    return done.stdout if done.returncode == 0 else None


def sharing(checkout: pathlib.Path, home: pathlib.Path,
            stated: dict[str, dict]) -> dict[tuple[str, str], str]:
    """A checkout made from a commit it shares, holding what its records state: each committed
    file is the commit's, and must be of the size stated, and of the content stated where a
    member's bytes or a literal digest pins it; modified and untracked files are its own. Each
    literal digest stated, replaced by the digest of the bytes held for it."""
    replaced = {}
    for path, fact in sorted(stated.items()):
        held = blob(checkout, home, path)
        data = fact.get("bytes") or made(fact["key"], fact["size"])
        state = fact["state"] or "committed"
        if state == "committed":
            pinned = "bytes" in fact or "literal" in fact
            if held is None or len(held) != fact["size"] or (pinned and held != data):
                raise blocked(f"{checkout.name} shares a commit that holds "
                              f"{'no file' if held is None else f'{len(held)} other bytes'} at "
                              f"{path}, where its records state a committed file of "
                              f"{fact['size']} bytes")
            data = held
        elif (state == "modified") != (held is not None):
            raise blocked(f"{checkout.name} shares a commit that "
                          f"{'holds' if held is not None else 'does not hold'} {path}, where its "
                          f"records state the file {state}")
        else:
            target = checkout / path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(data)
        if fact.get("literal"):
            replaced[("digest", fact["literal"])] = hashlib.sha256(data).hexdigest()
    return replaced


def switches(run, plan: Plan, built: dict, home: pathlib.Path) -> dict[str, str]:
    """Each commit a file edit writes into a branch's ref, and the commit made for it: HEAD's
    tree without the files the edits before the same step remove from that checkout."""
    steps = {step["name"]: step for step in run.built["steps"]}
    events = [event for event in run.built.get("world", {}).get("events", [])
              if event["kind"] == "file_edit"]
    found: dict[str, str] = {}
    for event in events:
        stated = str(event.get("bytes", "")).strip()
        if not event["path"].startswith(REFS) or not COMMIT.fullmatch(stated):
            continue
        key = plan.step_key(steps[event["before"]])
        checkout = built[plan.default() if key is None else key]
        gone = [other["path"] for other in events if other.get("absent")
                and other["before"] == event["before"] and not other["path"].startswith(".git")]
        index = run.workdir / "switch-index"
        git(checkout, home, "read-tree", "HEAD", index=index)
        if gone:
            git(checkout, home, "rm", "-r", "-q", "--cached", "--ignore-unmatch", "--", *gone,
                index=index)
        tree = git(checkout, home, "write-tree", index=index)
        index.unlink()
        branch = event["path"][len(REFS):]
        found[stated] = git(checkout, home, "commit-tree", tree, "-p", "HEAD", "-m",
                            f"the branch {branch} the person switches to")
    return found


def worked_in(templates: dict) -> set[str]:
    """The directories the scenario's preparations say they were composed in: a locator that is
    a path, not a remote."""
    return {record["observed"]["locator"] for record in templates.values()
            if record.get("kind") == PREPARATION and isinstance(record.get("observed"), dict)
            and str(record["observed"].get("locator", "")).startswith("/")}


def swapped(value, replaced: dict[tuple[str, str], str], field: str = ""):
    """The value with each stand-in replaced where its field is of the kind it stands for: a
    checkout path under `checkout`, a commit under `commit`, a file digest under a digest field."""
    if isinstance(value, dict):
        return {key: swapped(item, replaced, key) for key, item in value.items()}
    if isinstance(value, list):
        return [swapped(item, replaced, field) for item in value]
    if isinstance(value, str):
        return replaced.get((kind_of(field), value), value)
    return value


def kind_of(field: str) -> str:
    if field == PATH_KEY:
        return "path"
    if field == "commit":
        return "commit"
    if field == "locator":
        return "locator"
    return "digest" if field.endswith(("digest", "digests")) else ""
