"""The checkout: the repository working tree a scenario's person works in, made real.

A scenario states what a person's checkout holds only through the records that read it: the files
an observation reads from the working tree (path, size, git state, digest), the members a
repository-authored source's revision names (path, size, digest), and those of a source whose home
the scenario does not state at a path an observation reads from the tree, the branch, commit and
remote a repository binding observed, and the checkout a source selection names. Before the first
step this builds that one git checkout, and every stated value that stands for something only the
real checkout has is replaced by it wherever a field of its kind holds it, as the signing feature
replaces a public key:

  the checkout path a selection names  the directory built
  a file digest a record states        the sha256 of the bytes written at that path
  the commit a binding observed        the checkout's HEAD

A file whose digest names a member of the scenario holds that member's bytes; a file whose digest
the owner mints, or states, holds generated bytes of its stated size, the same bytes for the same
stated content. A file is committed unless an observation reads it `modified`, when HEAD holds
other bytes, or `untracked`, when it is not added. The branch and the remote are the ones a binding
observed, `main` when none says. The code under test runs in the checkout, and a file edit changes
it between steps.

The first state is what records state before anything changes a path: a record is dated by the
first step that sends, carries or returns it, or a record naming it by digest, and a fact about a
path a file edit changed by then is the edit's, not the first state's. A digest the owner mints for
a file it reads is known before the step that returns or carries it: the digest of the bytes at
that path then, which the answer must state. A manifest member whose size the owner mints names
a file the code under test writes: it is not in the first state, and after a step that code in
scope answers, each such member it returns must be the file at its path then, by digest and size.

What this cannot build is `blocked` by name: selections naming more than one checkout, one path
stated with two contents in the first state, and two bindings observing different branches or
remotes. A path another
record names that no selection does, such as a capture claiming input from another repository, is
left as stated.
"""
from __future__ import annotations

import hashlib
import os
import pathlib
import subprocess

import executor

OBSERVATION = "source_observation"
MANIFEST = "source_manifest"
HOME = "source_home"
BINDING = "repository_binding"
AUTHORED = "repository_authored"
PATH_KEY = "checkout"
SELECTION = "source_selection"
NEVER = float("inf")
BRANCH = "main"
IDENTITY = {"GIT_AUTHOR_NAME": "agent-bios conformance", "GIT_AUTHOR_EMAIL": "driver@localhost",
            "GIT_COMMITTER_NAME": "agent-bios conformance",
            "GIT_COMMITTER_EMAIL": "driver@localhost",
            "GIT_AUTHOR_DATE": "2026-01-01T00:00:00Z", "GIT_COMMITTER_DATE": "2026-01-01T00:00:00Z"}


def install(run) -> None:
    run.prepare_hooks.append(build)
    run.before_hooks.append(known_files)
    run.after_hooks.append(written_files)


def blocked(why: str):
    return executor.Stop(executor.BLOCKED, why)


def named_checkouts(templates: dict) -> set[str]:
    """The checkout paths the scenario's source selections name."""
    found: set[str] = set()
    for record in templates.values():
        for root in record.get("roots", []) if record.get("kind") == SELECTION else []:
            place = root.get("place") if isinstance(root, dict) else None
            if isinstance(place, dict) and isinstance(place.get(PATH_KEY), str):
                found.add(place[PATH_KEY])
    return found


def dated(run) -> dict[str, float]:
    """Each record's first step: the first that sends, carries or returns it, or that uses a
    record naming it by digest."""
    first: dict[str, float] = {}
    for index, step in enumerate(run.built["steps"]):
        result = step.get("result")
        for name in [step.get("request"), *step.get("carries", []), *step.get("returns", []),
                     result, run.receipt_of_result(result) if result else None]:
            if name and name not in first:
                first[name] = index
    changed = True
    while changed:
        changed = False
        for join in run.built["joins"]:
            named, by = join.get("digest_of"), join["record"]
            if named and by in first and first[by] < first.get(named, NEVER):
                first[named] = first[by]
                changed = True
    return first


def edits_of(run) -> dict[str, list[int]]:
    """Each path a file edit changes, and the steps it comes before."""
    index = {step["name"]: i for i, step in enumerate(run.built["steps"])}
    found: dict[str, list[int]] = {}
    for event in run.built.get("world", {}).get("events", []):
        if event["kind"] == "file_edit":
            found.setdefault(event["path"], []).append(index[event["before"]])
    return found


def places(run, name: str, record: dict) -> list[tuple[str, dict]]:
    """(pointer, entry) for each file a record states: an observation's tree reads, and the
    members of a repository-authored source's manifest."""
    if record.get("kind") == OBSERVATION:
        return [(f"/read/{i}", read) for i, read in enumerate(record.get("read", []))
                if read.get("read") == "tree"]
    if record.get("kind") != MANIFEST:
        return []
    source = record.get("source_id")
    if source in authored(run):
        return [(f"/members/{i}", member) for i, member in enumerate(record.get("members", []))]
    if source not in homed(run):
        tree = tree_paths(run)
        return [(f"/members/{i}", member) for i, member in enumerate(record.get("members", []))
                if member.get("path") in tree]
    return []


def homed(run) -> set:
    """The sources whose home the scenario states."""
    return {record.get("source_id") for record in run.templates.values()
            if record.get("kind") == HOME}


def tree_paths(run) -> set[str]:
    return {read["path"] for record in run.templates.values()
            if record.get("kind") == OBSERVATION
            for read in record.get("read", []) if read.get("read") == "tree"}


def authored(run) -> set:
    """The sources a home record states as repository-authored, whatever else is proposed."""
    return {record.get("source_id") for record in run.templates.values()
            if record.get("kind") == HOME and record.get("home", {}).get("mode") == AUTHORED}


def written(run) -> dict[str, dict[str, str]]:
    """Each manifest member naming a file the code under test writes, by record: pointer -> path.
    Its size is minted, so no one knows the file before the code writes it."""
    sized = {(join["record"], join["pointer"]) for join in run.built["joins"] if "minted" in join}
    found: dict[str, dict[str, str]] = {}
    for name, record in run.templates.items():
        if record.get("kind") != MANIFEST:
            continue
        for pointer, entry in places(run, name, record):
            if (name, pointer + "/size") in sized:
                found.setdefault(name, {})[pointer] = entry["path"]
    return found


def written_files(run, step: dict, answer: dict, how: str) -> None:
    """After a step code in scope answered, each file it says it wrote is the one at its path."""
    if run.checkout is None or how == "given":
        return
    for index, name in enumerate(step.get("returns", [])):
        record = answer.get("returned", [])[index]
        for pointer, path in run.written.get(name, {}).items():
            member = executor.at(record, pointer)[1]
            target = run.checkout / path
            data = target.read_bytes() if target.is_file() else None
            if data is None or not isinstance(member, dict) \
                    or member.get("digest") != hashlib.sha256(data).hexdigest() \
                    or member.get("size") != len(data):
                held = "no file" if data is None else \
                    f"{len(data)} bytes hashing to {hashlib.sha256(data).hexdigest()}"
                raise executor.Stop(executor.FAILED, f"{name}{pointer} says the code wrote {path} "
                                                     f"as {executor.shown(member)}, and the "
                                                     f"checkout holds {held} there",
                                    step=step["name"], record=name, pointer=pointer)


def file_digests(run) -> dict[str, tuple[str, str]]:
    """Each minted name that is the digest of a file the owner reads: (record, path)."""
    writes = written(run)
    found = {}
    for join in run.built["joins"]:
        if "minted" not in join or not join["pointer"].endswith("/digest"):
            continue
        record = join["record"]
        template = run.templates[record]
        for pointer, entry in places(run, record, template):
            if pointer in writes.get(record, {}):
                continue
            if join["pointer"] == pointer + "/digest":
                found.setdefault(join["minted"], (record, entry["path"]))
    return found


def known_files(run, step: dict) -> None:
    """Before a step, the digest of each file a record it carries or returns reads."""
    if run.checkout is None:
        return
    names = {step.get("request"), *step.get("carries", []), *step.get("returns", [])}
    learned = False
    for minted, (record, path) in run.file_digests.items():
        target = run.checkout / path
        if record in names and minted not in run.learned and target.is_file():
            run.learned[minted] = hashlib.sha256(target.read_bytes()).hexdigest()
            learned = True
    if learned:
        run.forget()


def facts(run) -> dict[str, dict]:
    """path -> {"size", "state", "key", "bytes"?, "literal"?} of the checkout's first state.

    `key` says which content the file holds: a member's name, a minted value, or a literal
    digest. A fact dated after a file edit of its path is the edit's."""
    first = dated(run)
    writes = written(run)
    changes = edits_of(run)
    joins = {(join["record"], join["pointer"]): join for join in run.built["joins"]}
    found: dict[str, dict] = {}

    def content(record: str, pointer: str, size: int, state: str | None) -> dict:
        join = joins.get((record, pointer))
        digest = executor.at(run.templates[record], pointer)[1]
        if join is not None and join.get("digest_of") in run.members:
            new = {"key": ("member", join["digest_of"]), "bytes": run.members[join["digest_of"]]}
        elif join is not None:
            new = {"key": ("minted", join.get("minted") or join.get("digest_of"))}
        else:
            new = {"key": ("literal", digest), "literal": digest}
        new.update(size=size, state=state)
        return new

    for name, record in run.templates.items():
        when = first.get(name, NEVER)
        for pointer, entry in places(run, name, record):
            path = entry["path"]
            if pointer in writes.get(name, {}):
                continue
            if any(before <= when for before in changes.get(path, [])):
                continue
            new = content(name, pointer + "/digest", entry["size"], entry.get("state"))
            held = found.get(path)
            if held is None:
                found[path] = new
                continue
            if (held["key"], held["size"]) != (new["key"], new["size"]):
                raise blocked(f"the scenario states two contents for {path} in its checkout's "
                              "first state, and a checkout that changes between steps without an "
                              "edit is not built yet")
            held["state"] = held["state"] or new["state"]
    return found


def made(key: tuple, size: int, variant: str = "") -> bytes:
    """Bytes of the stated size standing for one stated content."""
    seed = f"{variant}{key[0]} {key[1]}\n".encode()
    body = seed * (size // len(seed) + 1)
    return body[:size]


def git(checkout: pathlib.Path, home: pathlib.Path, *arguments: str) -> str:
    env = {key: value for key, value in os.environ.items() if not key.startswith("GIT_")}
    env.update(IDENTITY, HOME=str(home), GIT_CONFIG_NOSYSTEM="1")
    try:
        done = subprocess.run(["git", "-c", "commit.gpgsign=false",
                               "-c", "core.hooksPath=/dev/null", *arguments], cwd=checkout,
                              env=env, capture_output=True, text=True, timeout=60)
    except FileNotFoundError as error:
        raise blocked("git is not on PATH, so the driver cannot build the checkout") from error
    if done.returncode != 0:
        raise blocked(f"git {arguments[0]} exited {done.returncode}: {done.stderr.strip()}")
    return done.stdout.strip()


def observed(run) -> tuple[str, str | None, set[str]]:
    """(branch, remote, commits stated) the scenario's bindings observed."""
    branches, remotes, commits = set(), set(), set()
    joined = {(join["record"], join["pointer"]) for join in run.built["joins"]}
    for name, record in run.templates.items():
        seen = record.get("observed") if record.get("kind") == BINDING else None
        if not isinstance(seen, dict):
            continue
        if seen.get("branch"):
            branches.add(seen["branch"])
        if seen.get("locator"):
            remotes.add(seen["locator"])
        if seen.get("commit") and (name, "/observed/commit") not in joined:
            commits.add(seen["commit"])
    if len(branches) > 1 or len(remotes) > 1:
        raise blocked("the scenario's bindings observe more than one branch or remote, and a "
                      "checkout that changes branch between steps is not built yet")
    return (branches.pop() if branches else BRANCH), (remotes.pop() if remotes else None), commits


def build(run) -> None:
    named = named_checkouts(run.templates)
    if len(named) > 1:
        raise blocked(f"the scenario's selections name {len(named)} checkouts "
                      f"({', '.join(sorted(named))}), and a scenario with more than one is not "
                      "built yet")
    stated = facts(run)
    branch, remote, commits = observed(run)
    checkout = (run.workdir / "checkout").resolve()
    home = (run.workdir / "git-home").resolve()
    checkout.mkdir(parents=True)
    home.mkdir(parents=True)
    git(checkout, home, "init", "-q", "-b", branch)
    replaced: dict[tuple[str, str], str] = {("path", path): str(checkout) for path in named}
    later = []
    for path, fact in sorted(stated.items()):
        data = fact.get("bytes") or made(fact["key"], fact["size"])
        if fact.get("literal"):
            replaced[("digest", fact["literal"])] = hashlib.sha256(data).hexdigest()
        target = checkout / path
        target.parent.mkdir(parents=True, exist_ok=True)
        if fact["state"] == "untracked":
            later.append((target, data))
            continue
        if fact["state"] == "modified":
            later.append((target, data))
            data = made(fact["key"], fact["size"], "committed before ")
        target.write_bytes(data)
    git(checkout, home, "add", "-A")
    git(checkout, home, "commit", "-q", "--allow-empty", "--no-verify", "-m",
        "the checkout as the scenario states it")
    for target, data in later:
        target.write_bytes(data)
    if remote:
        git(checkout, home, "remote", "add", "origin", remote)
    head = git(checkout, home, "rev-parse", "HEAD")
    replaced.update({("commit", commit): head for commit in commits})
    for name, record in run.templates.items():
        run.templates[name] = swapped(record, replaced)
    run.checkout = run.cwd = checkout
    run.file_digests = file_digests(run)
    run.written = written(run)
    run.forget()


def swapped(value, replaced: dict[tuple[str, str], str], field: str = ""):
    """The value with each stand-in replaced where its field is of the kind it stands for: a
    checkout path under `checkout`, a commit under `commit`, a file digest under a digest field."""
    if isinstance(value, dict):
        return {key: swapped(item, replaced, key) for key, item in value.items()}
    if isinstance(value, list):
        return [swapped(item, replaced, field) for item in value]
    if isinstance(value, str):
        return replaced.get((kind_of(field), value), value)
    return value


def kind_of(field: str) -> str:
    if field == PATH_KEY:
        return "path"
    if field == "commit":
        return "commit"
    return "digest" if field.endswith(("digest", "digests")) else ""
