"""The checkout: the repository working tree a scenario's person works in, made real.

A scenario states what a person's checkout holds only through the records that read it: the files
an observation reads from the working tree (path, size, git state, digest), the members a
repository-authored source's revision names (path, size, digest), the branch, commit and remote a
repository binding observed, and the checkout path a selection or capture names. Before the first
step this builds one git checkout from those facts, and every stated value that stands for
something only the real checkout has is replaced by it everywhere, as the signing feature replaces
a public key:

  the checkout path a record names     the directory built
  a file digest a record states        the sha256 of the bytes written at that path
  the commit a binding observed        the checkout's HEAD

A file whose digest names a member of the scenario holds that member's bytes; a file whose digest
the owner mints, or states, holds generated bytes of its stated size, the same bytes for the same
stated digest. A file is committed unless an observation reads it `modified`, when HEAD holds other
bytes, or `untracked`, when it is not added. The branch and the remote are the ones a binding
observed, `main` when none says. A fact about the bytes a file edit writes is the edit's, not the
checkout's first state. The code under test runs in the checkout, and a file edit changes it
between steps.

What this cannot build is `blocked` by name: a scenario naming more than one checkout, one stating
two contents for one path, which a checkout that changes between steps without an edit would need,
and two bindings observing different branches or remotes.
"""
from __future__ import annotations

import hashlib
import os
import pathlib
import subprocess

import executor

OBSERVATION = "source_observation"
MANIFEST = "source_manifest"
HOME = "source_home"
BINDING = "repository_binding"
AUTHORED = "repository_authored"
PATH_KEY = "checkout"
BRANCH = "main"
IDENTITY = {"GIT_AUTHOR_NAME": "agent-bios conformance", "GIT_AUTHOR_EMAIL": "driver@localhost",
            "GIT_COMMITTER_NAME": "agent-bios conformance",
            "GIT_COMMITTER_EMAIL": "driver@localhost",
            "GIT_AUTHOR_DATE": "2026-01-01T00:00:00Z", "GIT_COMMITTER_DATE": "2026-01-01T00:00:00Z"}


def install(run) -> None:
    run.prepare_hooks.append(build)


def blocked(why: str):
    return executor.Stop(executor.BLOCKED, why)


def paths_named(value, found: set[str]) -> None:
    if isinstance(value, dict):
        for key, item in value.items():
            if key == PATH_KEY and isinstance(item, str):
                found.add(item)
            else:
                paths_named(item, found)
    elif isinstance(value, list):
        for item in value:
            paths_named(item, found)


def facts(run) -> dict[str, dict]:
    """path -> {"size", "state", "key", "bytes"?, "literal"?} the scenario's records state.

    `key` says which content the file holds: a member's name, a minted value, or a literal
    digest. A fact a file edit's bytes account for is left to the edit."""
    edited = {event.get("digest") for event in run.built.get("world", {}).get("events", [])
              if event["kind"] == "file_edit"}
    joins = {(join["record"], join["pointer"]): join for join in run.built["joins"]}
    authored = {record.get("source_id") for record in run.templates.values()
                if record.get("kind") == HOME and record.get("home", {}).get("mode") == AUTHORED}
    found: dict[str, dict] = {}

    def fact(record: str, pointer: str, path: str, size: int, state: str | None) -> None:
        join = joins.get((record, pointer))
        digest = executor.at(run.templates[record], pointer)[1]
        if join is None and digest in edited:
            return
        if join is not None and join.get("digest_of") in run.members:
            new = {"key": ("member", join["digest_of"]), "bytes": run.members[join["digest_of"]]}
        elif join is not None:
            new = {"key": ("minted", join.get("minted") or join.get("digest_of"))}
        else:
            new = {"key": ("literal", digest), "literal": digest}
        new.update(size=size, state=state)
        held = found.get(path)
        if held is None:
            found[path] = new
            return
        if (held["key"], held["size"]) != (new["key"], new["size"]):
            raise blocked(f"the scenario states two contents for {path} in its checkout, and a "
                          "checkout that changes between steps without an edit is not built yet")
        held["state"] = held["state"] or state

    for name, record in run.templates.items():
        if record.get("kind") == OBSERVATION:
            for index, read in enumerate(record.get("read", [])):
                if read.get("read") == "tree":
                    fact(name, f"/read/{index}/digest", read["path"], read["size"],
                         read["state"])
        if record.get("kind") == MANIFEST and record.get("source_id") in authored:
            for index, member in enumerate(record.get("members", [])):
                fact(name, f"/members/{index}/digest", member["path"], member["size"], None)
    return found


def made(key: tuple, size: int, variant: str = "") -> bytes:
    """Bytes of the stated size standing for one stated content."""
    seed = f"{variant}{key[0]} {key[1]}\n".encode()
    body = seed * (size // len(seed) + 1)
    return body[:size]


def git(checkout: pathlib.Path, home: pathlib.Path, *arguments: str) -> str:
    env = {key: value for key, value in os.environ.items() if not key.startswith("GIT_")}
    env.update(IDENTITY, HOME=str(home), GIT_CONFIG_NOSYSTEM="1")
    try:
        done = subprocess.run(["git", "-c", "commit.gpgsign=false",
                               "-c", "core.hooksPath=/dev/null", *arguments], cwd=checkout,
                              env=env, capture_output=True, text=True, timeout=60)
    except FileNotFoundError as error:
        raise blocked("git is not on PATH, so the driver cannot build the checkout") from error
    if done.returncode != 0:
        raise blocked(f"git {arguments[0]} exited {done.returncode}: {done.stderr.strip()}")
    return done.stdout.strip()


def observed(run) -> tuple[str, str | None, set[str]]:
    """(branch, remote, commits stated) the scenario's bindings observed."""
    branches, remotes, commits = set(), set(), set()
    joined = {(join["record"], join["pointer"]) for join in run.built["joins"]}
    for name, record in run.templates.items():
        seen = record.get("observed") if record.get("kind") == BINDING else None
        if not isinstance(seen, dict):
            continue
        if seen.get("branch"):
            branches.add(seen["branch"])
        if seen.get("locator"):
            remotes.add(seen["locator"])
        if seen.get("commit") and (name, "/observed/commit") not in joined:
            commits.add(seen["commit"])
    if len(branches) > 1 or len(remotes) > 1:
        raise blocked("the scenario's bindings observe more than one branch or remote, and a "
                      "checkout that changes branch between steps is not built yet")
    return (branches.pop() if branches else BRANCH), (remotes.pop() if remotes else None), commits


def build(run) -> None:
    named: set[str] = set()
    for record in run.templates.values():
        paths_named(record, named)
    if len(named) > 1:
        raise blocked(f"the scenario names {len(named)} checkouts ({', '.join(sorted(named))}), "
                      "and a scenario with more than one is not built yet")
    stated = facts(run)
    branch, remote, commits = observed(run)
    checkout = (run.workdir / "checkout").resolve()
    home = (run.workdir / "git-home").resolve()
    checkout.mkdir(parents=True)
    home.mkdir(parents=True)
    git(checkout, home, "init", "-q", "-b", branch)
    replaced: dict[str, str] = {path: str(checkout) for path in named}
    later = []
    for path, fact in sorted(stated.items()):
        data = fact.get("bytes") or made(fact["key"], fact["size"])
        if fact.get("literal"):
            replaced[fact["literal"]] = hashlib.sha256(data).hexdigest()
        target = checkout / path
        target.parent.mkdir(parents=True, exist_ok=True)
        if fact["state"] == "untracked":
            later.append((target, data))
            continue
        if fact["state"] == "modified":
            later.append((target, data))
            data = made(fact["key"], fact["size"], "committed before ")
        target.write_bytes(data)
    git(checkout, home, "add", "-A")
    git(checkout, home, "commit", "-q", "--allow-empty", "--no-verify", "-m",
        "the checkout as the scenario states it")
    for target, data in later:
        target.write_bytes(data)
    if remote:
        git(checkout, home, "remote", "add", "origin", remote)
    head = git(checkout, home, "rev-parse", "HEAD")
    replaced.update({commit: head for commit in commits})
    for name, record in run.templates.items():
        run.templates[name] = swapped(record, replaced)
    run.checkout = run.cwd = checkout
    run.forget()


def swapped(value, replaced: dict[str, str]):
    if isinstance(value, dict):
        return {key: swapped(item, replaced) for key, item in value.items()}
    if isinstance(value, list):
        return [swapped(item, replaced) for item in value]
    return replaced.get(value, value) if isinstance(value, str) else value
