#!/usr/bin/env python3
"""Project instances/graph.json into ONTOLOGY_MAP.html.

Closes a GR-1 violation this ontology committed against its own rule: the page used
to carry its own copy of the entity/position data, the golden-relationship table, and
a hand-typed version of the extractor's deploy/verify result. Three restatements of
one truth, none of them checked. Now graph.json is the only canonical site, the GR-4
table comes from live extraction, and `--check` fails when the page is stale.

Layout is a view and stays here as a template; every number and row is injected.

Usage: emit-map.py [--check] [-o OUT]
"""
from __future__ import annotations

import argparse
import collections
import html
import importlib.util
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
GRAPH = HERE / "instances" / "graph.json"
DEFAULT_OUT = HERE / "ONTOLOGY_MAP.html"

STATUS_CLASS = {"derived": "ok", "gated": "risk", "partial": "info",
                "unguarded": "warn", "violated": "risk"}
GUARD_ORDER = ("unguarded", "partial", "gated", "derived")


def extractors() -> dict:
    spec = importlib.util.spec_from_file_location("onto_extract", HERE / "extract.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return {name: fn() for name, fn in mod.EXTRACTORS.items()}


def e(s) -> str:
    return html.escape(str(s), quote=False)


def build(graph: dict, ev: dict) -> str:
    ents, rels, grs = graph["entities"], graph["relationships"], graph["golden_relationships"]
    fams = graph["families"]
    guards = collections.Counter(x["guard"] for x in ents)
    unguarded = guards["unguarded"]
    no_p6 = sum(1 for x in ents if "P6" not in x["pos"])
    if unguarded != no_p6:
        print(f"FAIL: graph violates its own invariant — {unguarded} unguarded vs {no_p6} without P6",
              file=sys.stderr)
        sys.exit(1)

    gr4 = ev["gr4_deploy_verify"]
    gr_status = collections.Counter(g["status"] for g in grs)
    d = graph["derived"]

    # ---- entity payload for the explorer (the ONLY copy, injected) ----
    payload = json.dumps(
        [{"name": x["class"], "fam": x["family"], "pos": x["pos"], "guard": x["guard"],
          "anchor": x["anchor"], "note": x["desc"]} for x in ents],
        ensure_ascii=False, indent=1,
    )
    fam_labels = json.dumps({k: f'{k} · {v["label"]}' for k, v in fams.items()}, ensure_ascii=False)

    # ---- SVG golden-relationship columns ----
    def gr_line(g: dict) -> str:
        colour = {"derived": "#18794e", "gated": "#b42318", "partial": "#0e7490",
                  "unguarded": "#b54708", "violated": "#b54708"}[g["status"]]
        label = f'{g["id"]:<6}{g["title"][:26]:<28}{g["binds"]}'
        return colour, e(label)

    ordered = sorted(grs, key=lambda g: ({"derived": 0, "gated": 1, "partial": 2,
                                          "unguarded": 3, "violated": 4}[g["status"]], g["id"]))
    left, right = ordered[:6], ordered[6:]

    def svg_col(items, x):
        out = []
        for i, g in enumerate(items):
            colour, label = gr_line(g)
            out.append(f'        <text class="gr" x="0" y="{i * 22}" fill="{colour}">{label}</text>')
        return f'      <g transform="translate({x},462)">\n' + "\n".join(out) + "\n      </g>"

    gr_rows = "\n".join(
        f'      <tr><td>{g["id"]} {e(g["title"])}</td><td>{e(g["binds"])}</td>'
        f'<td>{e(g["verification"])}</td>'
        f'<td class="{STATUS_CLASS[g["status"]]}">{g["status"]}</td></tr>'
        for g in grs
    )

    gr4_rows = "\n".join(
        f'      <tr><td><code>{e(r["dst"])}</code> :{r["deploy_line"]}</td>'
        f'<td>{("".join(f"<code>{a['fn']}</code> :{a['line']}" for a in r["assertions"][:1]) or "—")}</td>'
        f'<td class="{"ok" if r["strength"] == "byte-identity" else ("risk" if not r["covered"] else "")}">'
        f'{r["strength"] or "none"}</td></tr>'
        for r in gr4["rows"]
    )

    buttons = "\n".join(
        f'    <button data-guard="{g}" aria-pressed="false">{g.title()} '
        f'<span class="count">{guards[g]}</span></button>'
        for g in GUARD_ORDER
    )

    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>agent-bios Ontology Map</title>
  <!-- GENERATED by ontology/emit-map.py from ontology/instances/graph.json. Do not edit:
       emit-map.py --check fails on any hand edit, the way the codex/ mirrors are held. -->
  <style>
    :root {{ color-scheme: light; --ink:#17202a; --muted:#586474; --line:#cbd3dc; --bg:#f7f8fa; --ok:#18794e; --risk:#b42318; --warn:#b54708; --info:#0e7490; }}
    * {{ box-sizing: border-box; }}
    body {{ margin:0; color:var(--ink); background:var(--bg); font:14px/1.45 ui-sans-serif,system-ui,-apple-system,sans-serif; }}
    main {{ width:min(1180px,calc(100% - 32px)); margin:0 auto; padding:28px 0 48px; }}
    h1 {{ margin:0 0 8px; font-size:28px; }}
    h2 {{ margin:28px 0 10px; font-size:18px; }}
    p {{ margin:6px 0; }}
    .lede {{ color:var(--muted); max-width:920px; }}
    .status {{ display:grid; grid-template-columns:repeat(5,minmax(0,1fr)); border:1px solid var(--line); background:#fff; margin-top:20px; }}
    .status div {{ min-width:0; padding:12px; border-right:1px solid var(--line); }}
    .status div:last-child {{ border-right:0; }}
    .status b {{ display:block; font-size:11px; color:var(--muted); text-transform:uppercase; }}
    .status span {{ display:block; margin-top:4px; overflow-wrap:anywhere; }}
    .ok {{ color:var(--ok); }} .risk {{ color:var(--risk); }} .warn {{ color:var(--warn); }} .info {{ color:var(--info); }}
    .blueprint {{ overflow-x:auto; border:1px solid var(--line); background:#fff; }}
    svg {{ display:block; width:100%; min-width:980px; height:auto; }}
    table {{ width:100%; border-collapse:collapse; background:#fff; }}
    th,td {{ padding:9px 10px; border:1px solid var(--line); text-align:left; vertical-align:top; }}
    th {{ background:#eef1f4; }}
    code {{ font:12px ui-monospace,SFMono-Regular,Menlo,monospace; overflow-wrap:anywhere; }}
    .explorer {{ display:grid; grid-template-columns:minmax(0,1fr) 340px; gap:16px; align-items:start; }}
    .controls {{ display:flex; flex-wrap:wrap; gap:8px; margin:0 0 12px; }}
    .controls input {{ flex:1 1 220px; padding:8px 10px; border:1px solid var(--line); background:#fff; font:14px inherit; }}
    .controls button {{ padding:8px 11px; border:1px solid var(--line); background:#fff; cursor:pointer; font:12px inherit; }}
    .controls button[aria-pressed="true"] {{ background:var(--ink); color:#fff; border-color:var(--ink); }}
    .bands {{ border:1px solid var(--line); background:#fff; padding:4px 12px 12px; }}
    .band > h3 {{ margin:14px 0 6px; font-size:12px; text-transform:uppercase; color:var(--muted); letter-spacing:.04em; }}
    .chips {{ display:flex; flex-wrap:wrap; gap:6px; }}
    .chip {{ display:flex; align-items:center; gap:6px; padding:5px 9px; border:1px solid var(--line); border-left-width:4px; background:#fff; cursor:pointer; font:13px inherit; text-align:left; }}
    .chip:hover, .chip:focus-visible {{ background:#eef1f4; }}
    .chip[aria-pressed="true"] {{ background:var(--ink); color:#fff; }}
    .chip .reach {{ font:11px ui-monospace,monospace; opacity:.72; letter-spacing:.06em; }}
    .g-derived {{ border-left-color:#18794e; }} .g-gated {{ border-left-color:#b42318; }}
    .g-partial {{ border-left-color:#0e7490; }} .g-unguarded {{ border-left-color:#b54708; }}
    .inspector {{ border:1px solid var(--line); background:#fff; padding:14px; position:sticky; top:16px; }}
    .inspector h3 {{ margin:0 0 2px; font-size:16px; }}
    .inspector dt {{ font-size:11px; text-transform:uppercase; color:var(--muted); margin-top:11px; }}
    .inspector dd {{ margin:3px 0 0; }}
    .pos {{ display:flex; gap:4px; margin-top:5px; }}
    .pos span {{ flex:1; text-align:center; padding:4px 0; border:1px solid var(--line); font:11px ui-monospace,monospace; color:var(--muted); }}
    .pos span.on {{ background:#e7eaee; color:var(--ink); border-color:#667085; font-weight:700; }}
    .pos span.gap {{ background:#fff4ed; border-color:#b54708; color:#b54708; }}
    .count {{ color:var(--muted); font-size:12px; }}
    @media (max-width:860px) {{ .status,.explorer {{ grid-template-columns:1fr; }} .inspector {{ position:static; }} }}
  </style>
</head>
<body>
<main>
  <h1>agent-bios ontology map</h1>
  <p class="lede">Generated from <code>ontology/instances/graph.json</code> by <code>ontology/emit-map.py</code>, with the deploy/verify table taken from live extraction rather than restated. {len(ents)} entities on the concept axis, six positions on the manifestation axis, {len(grs)} golden relationships. Built to the repo's blueprint discipline; interaction after an ontology explorer — search, filter, click to inspect. Self-contained, no external assets.</p>

  <section class="status" aria-label="Current status">
    <div><b>Judgment question</b><span>Change one concept — how far do the obligations reach, and which of them is anything actually holding?</span></div>
    <div><b>Coverage</b><span>{len(ents)} entities across {len(fams)} families; {len(rels)} obligation edges over {len(set(r["kind"] for r in rels))} kinds; {len(grs)} golden relationships</span></div>
    <div><b>Held against code</b><span class="ok"><code>gates/check-ontology.py</code> — anchors, derived counts, edge integrity, graph health, projection freshness; 7 negative controls</span></div>
    <div><b>Derived from source</b><span>{d["deploy_targets"]} deploy targets · {d["guides"]} guides · {d["tier_bindings"]} tier bindings · {d["subcommands"]} subcommands · {d["payload_files"]} payload paths</span></div>
    <div><b>Main risk</b><span class="risk">{unguarded} of {len(ents)} entities carry no P6 assertion at all; {gr_status["unguarded"]} of {len(grs)} golden relationships are unguarded and GR-4 is violated</span></div>
  </section>

  <h2>Blueprint — where authority flows, and where nothing is watching</h2>
  <div class="blueprint">
    <svg viewBox="0 0 1500 700" role="img" aria-labelledby="bp-title bp-desc">
      <title id="bp-title">Manifestation positions and the golden relationships that bind them</title>
      <desc id="bp-desc">Authority flows left to right from canonical through derived, packaged, deployed and consumed. A separate assertion band carries the golden relationships, coloured by enforcement.</desc>
      <defs>
        <marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0 0L10 5L0 10Z" fill="#506070"/></marker>
        <marker id="green-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0 0L10 5L0 10Z" fill="#18794e"/></marker>
        <style>
          .t{{font:600 20px ui-sans-serif,system-ui;fill:#17202a}}
          .s{{font:14px ui-sans-serif,system-ui;fill:#344054}}
          .m{{font:12px ui-monospace,monospace;fill:#344054}}
          .lane{{font:700 13px ui-sans-serif,system-ui;fill:#586474}}
          .gr{{font:11px ui-monospace,monospace;white-space:pre}}
          .node{{stroke-width:2}}
          .flow{{fill:none;stroke:#506070;stroke-width:2;marker-end:url(#arrow)}}
          .authority{{fill:none;stroke:#18794e;stroke-width:3;marker-end:url(#green-arrow)}}
          .bind-derived{{fill:none;stroke:#18794e;stroke-width:2.5}}
          .bind-partial{{fill:none;stroke:#0e7490;stroke-width:2.5;stroke-dasharray:6 4}}
          .bind-unguarded{{fill:none;stroke:#b54708;stroke-width:2.5;stroke-dasharray:2 5}}
        </style>
      </defs>

      <text class="t" x="36" y="38">Change one concept — how far do the obligations reach, and which is anything actually holding?</text>

      <g transform="translate(36,58)">
        <rect x="0" y="0" width="1428" height="34" fill="#f7f8fa" stroke="#cbd3dc"/>
        <line class="bind-derived"   x1="14"  y1="17" x2="52"  y2="17"/><text class="gr" x="58"  y="21" fill="#18794e">derived — drift impossible ({gr_status["derived"]})</text>
        <line class="bind-partial"   x1="330" y1="17" x2="368" y2="17"/><text class="gr" x="374" y="21" fill="#0e7490">gated or partial ({gr_status["gated"] + gr_status["partial"]})</text>
        <line class="bind-unguarded" x1="620" y1="17" x2="658" y2="17"/><text class="gr" x="664" y="21" fill="#b54708">unguarded — obligation known, nothing enforces it ({gr_status["unguarded"] + gr_status["violated"]})</text>
      </g>

      <text class="lane" x="36" y="130">AUTHORITY FLOW  ·  P1 → P5</text>
      <rect class="node" x="36"   y="146" width="252" height="96" rx="5" fill="#dbeafe" stroke="#2563eb"/>
      <text class="s" x="54" y="174"><tspan font-weight="700">P1 canonical</tspan><tspan x="54" dy="22">authored, no upstream</tspan><tspan class="m" x="54" dy="21">exactly one per entity (GR-1)</tspan></text>
      <rect class="node" x="322"  y="146" width="252" height="96" rx="5" fill="#dcfce7" stroke="#18794e"/>
      <text class="s" x="340" y="174"><tspan font-weight="700">P2 derived</tspan><tspan x="340" dy="22">emitted by a named producer</tspan><tspan class="m" x="340" dy="21">codex/, ko/codex/, promotions</tspan></text>
      <rect class="node" x="608"  y="146" width="252" height="96" rx="5" fill="#e7eaee" stroke="#667085"/>
      <text class="s" x="626" y="174"><tspan font-weight="700">P3 packaged</tspan><tspan x="626" dy="22">in the shipped payload</tspan><tspan class="m" x="626" dy="21">{d["payload_files"]} files[] paths</tspan></text>
      <rect class="node" x="894"  y="146" width="252" height="96" rx="5" fill="#e7eaee" stroke="#667085"/>
      <text class="s" x="912" y="174"><tspan font-weight="700">P4 deployed</tspan><tspan x="912" dy="22">written onto a machine</tspan><tspan class="m" x="912" dy="21">{d["deploy_targets"]} deploy targets</tspan></text>
      <rect class="node" x="1180" y="146" width="284" height="96" rx="5" fill="#f3e8ff" stroke="#7c3aed"/>
      <text class="s" x="1198" y="174"><tspan font-weight="700">P5 consumed</tspan><tspan x="1198" dy="22">a branch that reads it and acts</tspan><tspan class="m" x="1198" dy="21">absent ⇒ inert (GR-6)</tspan></text>
      <path class="authority" d="M288 194 H316"/>
      <path class="flow" d="M574 194 H602"/>
      <path class="flow" d="M860 194 H888"/>
      <path class="flow" d="M1146 194 H1174"/>

      <text class="lane" x="36" y="292">CONCEPT AXIS  ·  {len(ents)} entities, attributed by primary enforcement point</text>
      <g transform="translate(36,306)">
{chr(10).join(f'        <rect x="{i * 290}" y="0" width="278" height="62" rx="5" fill="#fff" stroke="#cbd3dc"/><text class="s" x="{i * 290 + 16}" y="26"><tspan font-weight="700">{k} {e(v["label"])[:24]}</tspan><tspan class="m" x="{i * 290 + 16}" dy="20">{sum(1 for x in ents if x["family"] == k)} entities</tspan></text>' for i, (k, v) in enumerate(fams.items()))}
      </g>

      <text class="lane" x="36" y="424">ASSERTION BAND  ·  P6 binds positions rather than sitting in the flow</text>
      <rect x="36" y="440" width="1428" height="228" rx="5" fill="#fffaf5" stroke="#cbd3dc"/>
{svg_col(left, 56)}
{svg_col(right, 770)}
      <text class="m" x="56" y="690">Unguarded is not "fine" and not "broken" — it is unknown. {gr_status["unguarded"] + gr_status["violated"]} of {len(grs)}, first counted 2026-07-29.</text>
    </svg>
  </div>

  <h2>Entity explorer</h2>
  <div class="controls">
    <input id="q" type="search" placeholder="Search entities, anchors, notes…" aria-label="Search entities">
    <button data-guard="all" aria-pressed="true">All <span class="count">{len(ents)}</span></button>
{buttons}
  </div>
  <div class="explorer">
    <div class="bands" id="bands"></div>
    <aside class="inspector" id="inspector" aria-live="polite"></aside>
  </div>

<script>
const P = ["P1","P2","P3","P4","P5","P6"];
const FAM = {fam_labels};
const E = {payload};

const bands = document.getElementById("bands");
const insp  = document.getElementById("inspector");
const q     = document.getElementById("q");
let guardFilter = "all", selected = null;

function reachLabel(x){{ return P.map(p => x.pos.includes(p) ? p[1] : "·").join(""); }}

function show(x){{
  selected = x;
  insp.innerHTML = "";
  if(!x){{ insp.innerHTML = '<h3>Select an entity</h3><p class="count">Click any chip to inspect its manifestation set, guard status, and what breaks when a position is missed.</p>'; return; }}
  const h = document.createElement("h3"); h.textContent = x.name; insp.append(h);
  const sub = document.createElement("p"); sub.className="count"; sub.textContent = FAM[x.fam]; insp.append(sub);
  const posRow = P.map(p => {{
    const on = x.pos.includes(p);
    return `<span class="${{on?"on":(p==="P6"?"gap":"")}}">${{p}}</span>`;
  }}).join("");
  const dl = document.createElement("dl");
  dl.innerHTML =
    `<dt>Manifestation set</dt><dd><div class="pos">${{posRow}}</div></dd>` +
    `<dt>Guard status</dt><dd>${{x.guard}}${{x.pos.includes("P6")?"":" — no P6 assertion: unknown, not fine"}}</dd>` +
    `<dt>Anchor</dt><dd><code>${{x.anchor}}</code></dd>` +
    `<dt>Missed when</dt><dd>${{x.note}}</dd>`;
  insp.append(dl);
}}

function render(){{
  const term = q.value.trim().toLowerCase();
  bands.innerHTML = "";
  let shown = 0;
  for(const [fam,label] of Object.entries(FAM)){{
    const items = E.filter(x => x.fam===fam
      && (guardFilter==="all" || x.guard===guardFilter)
      && (!term || (x.name+" "+x.anchor+" "+x.note).toLowerCase().includes(term)));
    if(!items.length) continue;
    shown += items.length;
    const band = document.createElement("section"); band.className="band";
    const h = document.createElement("h3"); h.textContent = `${{label}} — ${{items.length}}`; band.append(h);
    const wrap = document.createElement("div"); wrap.className="chips";
    for(const x of items){{
      const b = document.createElement("button");
      b.className = `chip g-${{x.guard}}`; b.type = "button";
      b.setAttribute("aria-pressed", String(selected && selected.name===x.name));
      b.innerHTML = `<span>${{x.name}}</span><span class="reach">${{reachLabel(x)}}</span>`;
      b.addEventListener("click", () => {{ show(x); render(); }});
      wrap.append(b);
    }}
    band.append(wrap); bands.append(band);
  }}
  if(!shown) bands.innerHTML = '<p class="count" style="padding:12px 0">No entity matches that filter.</p>';
}}

// The invariant emit-map.py also refuses to publish past: unguarded <=> no P6.
(function assertInvariant(){{
  const bad = E.filter(x => (x.guard === "unguarded") !== !x.pos.includes("P6"));
  const el = document.createElement("p");
  el.style.cssText = "margin:0 0 12px;font:12px ui-monospace,monospace";
  if(bad.length){{
    el.className = "risk";
    el.textContent = `INVARIANT VIOLATED — guard/P6 disagree for: ${{bad.map(x=>x.name).join(", ")}}`;
  }} else {{
    el.className = "ok";
    el.textContent = `invariant holds — "unguarded" and "no P6 assertion" are the same ${{E.filter(x=>x.guard==="unguarded").length}} entities`;
  }}
  document.querySelector(".controls").after(el);
}})();

for(const btn of document.querySelectorAll(".controls button")){{
  btn.addEventListener("click", () => {{
    guardFilter = btn.dataset.guard;
    document.querySelectorAll(".controls button").forEach(b => b.setAttribute("aria-pressed", String(b===btn)));
    render();
  }});
}}
q.addEventListener("input", render);
show(null); render();
</script>

  <h2>Golden relationships</h2>
  <table>
    <thead><tr><th>Rule</th><th>Binds</th><th>Verification</th><th>Status</th></tr></thead>
    <tbody>
{gr_rows}
    </tbody>
  </table>

  <h2>GR-4, computed</h2>
  <p class="lede">Not restated — <code>ontology/extract.py</code> reads the real <code>deploy_file</code>/<code>deploy_glob</code> and <code>verify_match</code>/<code>verify_present</code> call sites at generation time. {gr4["deploy_count"]} deploy writes, {len(gr4["uncovered"])} with no assertion.</p>
  <table>
    <thead><tr><th>P4 write</th><th>P6 assertion</th><th>Strength</th></tr></thead>
    <tbody>
{gr4_rows}
    </tbody>
  </table>

  <p class="lede" style="margin-top:24px">Canonical source <code>ontology/instances/graph.json</code>; prose in <code>domain_scope.md</code>, <code>concepts.md</code>, <code>structure_spec.md</code>, <code>dependency_rules.md</code>. Held by <code>gates/check-ontology.py</code>, wired into <code>gates/check-parity.sh</code>.</p>
</main>
</body>
</html>
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if the page has drifted from its source")
    ap.add_argument("-o", "--out", type=pathlib.Path, default=DEFAULT_OUT)
    args = ap.parse_args()

    graph = json.loads(GRAPH.read_text(encoding="utf-8"))
    page = build(graph, extractors())

    if args.check:
        if not args.out.is_file():
            print(f"FAIL: {args.out} does not exist (run emit-map.py)", file=sys.stderr)
            sys.exit(1)
        if args.out.read_text(encoding="utf-8") != page:
            print(f"FAIL: {args.out} is stale vs instances/graph.json (run emit-map.py)", file=sys.stderr)
            sys.exit(1)
        print(f"emit-map: OK ({args.out.name} matches graph.json)")
        return

    args.out.write_text(page, encoding="utf-8")
    print(f"emit-map: wrote {args.out} — {len(graph['entities'])} entities, "
          f"{len(graph['relationships'])} edges, {len(graph['golden_relationships'])} golden relationships")


if __name__ == "__main__":
    main()
