"""Scenarios: the joined bytes a case runs, generated from a short spec.

A case that drives an operation needs more than records that each pass their schema. The request
must name the digest of the payload beside it, the result must answer that request, and an id
must be the same one from step to step. Written by hand those joins drift, and two workers reading
one case fill them in differently. So a case's scenario is a spec (`spec.json`, shaped by
`scenario.schema.json`) and this module writes the joined bytes (`scenario.json`) beside it. The
spec, this module and the generated file together are the case's fixture.

Every record in a spec is a contract example with the leaves the case changes, so the examples
are the vocabulary and a spec states only differences. A string value may name instead of state:

  "@name"          the id `name`: its prefix and 32 hex digits derived from the case and the name
  "#name"          the digest of the record `name` as this scenario builds it
  "$shape:name"    a value the owner mints — an id it assigns, a time, a count, the digest of
                   what it wrote. Its first place is in a record a step's answer returns. The
                   generated bytes carry a stand-in that satisfies the schema there (shape is an
                   id prefix, `digest`, `instant` or `integer`).

`joins` in the generated file lists every place a name was resolved, so a driver can put the
owner's real value in each minted place, and recompute every digest over it, before submitting.
A digest of a record a step returns is likewise the digest of what the owner actually returned.

What can be decided from the spec alone is checked here and fails by name:
  - every record resolves, and every name it uses is defined;
  - an answered step's request and payload pass their schemas in submit mode and every other
    record it carries passes in stored mode; a refused step's records fail with exactly the
    refusals it states;
  - the digests a request names are exactly those of the records the step carries, apart from
    records an earlier step returned and values it minted;
  - the payload is a kind its operation takes (no payload when it takes none), and every record
    the answer returns is a kind the operation returns;
  - the result built from the answer passes the result schema, so an answer the contract cannot
    give — a commit beside a gap that prevents one — cannot be written in a spec either;
  - a minted value is used only after the step whose answer first returns it.

  python3 gates/workenv/scenarios.py           # write every scenario.json from its spec
  python3 gates/workenv/scenarios.py --check   # fail when any scenario.json differs from its spec
"""
from __future__ import annotations

import hashlib
import json
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2]))
from workenv.contracts import canonical, errors, examples, records  # noqa: E402
from workenv.contracts.schema import STORED, SUBMIT, load_schema  # noqa: E402

HERE = pathlib.Path(__file__).resolve().parent
SCENARIOS = HERE / "fixtures" / "scenarios"
SCHEMA = HERE / "scenario.schema.json"
SPEC, GENERATED = "spec.json", "scenario.json"
STAND_IN_INSTANT = "2000-01-01T00:00:00Z"
NAMED = re.compile(r"([@#])([a-z][a-z0-9]*(?:_[a-z0-9]+)*)\Z")
MINTED = re.compile(r"\$(digest|instant|integer|[a-z]{3}):([a-z][a-z0-9]*(?:_[a-z0-9]+)*)\Z")
# The request fields that name another record by digest.
NAMING = ("payload_digest", "recipient_digest", "policy_digests", "control_digests",
          "proof_digests")


class ScenarioError(ValueError):
    """A spec this module cannot turn into joined bytes, named."""


def operations() -> dict[str, dict]:
    """operation -> {"takes": kinds, "returns": kinds}, joined from the contract modules."""
    return {name: row for module in errors.OWNERS
            for name, row in getattr(module, "OPERATIONS", {}).items()}


def _hex(*parts: str) -> str:
    return hashlib.sha256("/".join(parts).encode()).hexdigest()


def _segments(pointer: str) -> list[str]:
    return [part.replace("~1", "/").replace("~0", "~") for part in pointer.split("/")[1:]]


def _violations(value, mode: str, schemas: dict) -> list[dict]:
    """Refusals of one value read as a contract record, in the shape a spec states them."""
    try:
        identifier = records.resolve(value, records.registry(schemas))
    except records.RecordError as error:
        return [{"code": error.code, "pointer": error.pointer}]
    return [{"code": v.code, "pointer": v.pointer}
            for v in schemas[identifier].validate(value, mode)]


class _Scenario:
    def __init__(self, spec: dict, schemas: dict):
        self.case = spec["case"]
        self.schemas = schemas
        self.ids = {row["name"]: f"{row['prefix']}_{_hex(self.case, row['name'])[:32]}"
                    for row in spec["ids"]}
        self.specs = {row["name"]: row for row in spec["records"]}
        self.built: dict[str, object] = {}
        self.digests: dict[str, str] = {}
        self.uses: dict[str, set[str]] = {}      # record -> minted names it rests on
        self.minted: dict[str, str] = {}         # minted name -> shape
        self.joins: list[dict] = []
        self.open: list[str] = []
        self.returned: set[str] = set()          # records an earlier step's answer returned

    def fail(self, where: str, detail: str) -> None:
        raise ScenarioError(f"{self.case} {where}: {detail}")

    def stand_in(self, shape: str, name: str):
        if shape == "digest":
            return _hex(self.case, "minted", name)
        if shape == "instant":
            return STAND_IN_INSTANT
        if shape == "integer":
            return 1
        return f"{shape}_{_hex(self.case, 'minted', name)[:32]}"

    def value(self, raw, record: str, pointer: str):
        if isinstance(raw, list):
            return [self.value(item, record, f"{pointer}/{i}") for i, item in enumerate(raw)]
        if not isinstance(raw, str):
            return raw
        minted = MINTED.match(raw)
        if minted:
            shape, name = minted.groups()
            if self.minted.setdefault(name, shape) != shape:
                self.fail(f"{record}{pointer}",
                          f"${name} minted as {self.minted[name]} and {shape}")
            self.uses[record].add(name)
            self.joins.append({"record": record, "pointer": pointer, "minted": name})
            return self.stand_in(shape, name)
        named = NAMED.match(raw)
        if not named:
            return raw
        sigil, name = named.groups()
        if sigil == "@":
            if name not in self.ids:
                self.fail(f"{record}{pointer}", f"no id named {name!r}")
            return self.ids[name]
        digest = self.digest(name)
        self.uses[record] |= self.uses[name]
        self.joins.append({"record": record, "pointer": pointer, "digest_of": name})
        return digest

    def digest(self, name: str) -> str:
        self.record(name)
        return self.digests[name]

    def record(self, name: str):
        if name in self.built:
            return self.built[name]
        if name not in self.specs:
            self.fail(name, "no record by that name")
        if name in self.open:
            self.fail(name, f"names its own digest through {' -> '.join(self.open)}")
        self.open.append(name)
        row = self.specs[name]
        path = examples.EXAMPLES / row["from"]
        if not path.is_file():
            self.fail(name, f"no example {row['from']}")
        value = canonical.parse(path.read_bytes())
        self.uses[name] = set()
        for pointer in row.get("drop", []):
            parent, key = self.locate(value, pointer, name, create=False)
            del parent[key]
        for change in row.get("set", []):
            parent, key = self.locate(value, change["pointer"], name, create=True)
            at = "/".join(change["pointer"].split("/")[:-1])
            if isinstance(parent, list) and key == len(parent):
                parent.append(self.value(change["value"], name, f"{at}/{key}"))
            else:
                parent[key] = self.value(change["value"], name, f"{at}/{key}")
        self.open.pop()
        self.built[name] = value
        self.digests[name] = canonical.digest_of(value)
        return value

    def locate(self, document, pointer: str, name: str, create: bool):
        *path, last = _segments(pointer)
        node = document
        for part in path:
            if isinstance(node, list):
                if not part.isdigit() or int(part) >= len(node):
                    self.fail(f"{name}{pointer}", f"no item {part}")
                node = node[int(part)]
            elif isinstance(node, dict):
                if part not in node:
                    if not create:
                        self.fail(f"{name}{pointer}", f"no field {part}")
                    node[part] = {}
                node = node[part]
            else:
                self.fail(f"{name}{pointer}", "passes through a value that is not a container")
        if isinstance(node, list):
            if last == "-" and create:
                return node, len(node)
            if not last.isdigit() or int(last) >= len(node):
                self.fail(f"{name}{pointer}", f"no item {last}")
            return node, int(last)
        if not isinstance(node, dict) or (not create and last not in node):
            self.fail(f"{name}{pointer}", f"no field {last}")
        return node, last

    def named_by(self, request: dict) -> list[str]:
        found = []
        for field in NAMING:
            value = request.get(field, [])
            found.extend(value if isinstance(value, list) else [value])
        return found

    def step(self, row: dict, table: dict, defined: set[str], result_schema) -> tuple[dict, list]:
        name = row["name"]
        request = self.record(row["request"])
        carried = {n: self.record(n) for n in row["carries"]}
        if request.get("kind") != "operation_request":
            self.fail(name, f"{row['request']} is not an operation_request")
        early = set().union(*(self.uses[n] for n in [row["request"], *row["carries"]])) - defined
        if early:
            self.fail(name, f"uses {sorted(early)} before any step returns them")
        stand_ins = ({self.stand_in("digest", m) for m, shape in self.minted.items()
                      if shape == "digest" and m in defined}
                     | {self.digests[r] for r in self.returned})
        named = self.named_by(request)
        by_digest = {self.digests[n]: n for n in carried}
        loose = [d for d in named if d not in by_digest and d not in stand_ins]
        if loose:
            self.fail(name, f"the request names {loose}, which the step does not carry and no "
                            "earlier step returned or minted")
        unnamed = sorted(n for n, d in ((n, self.digests[n]) for n in carried) if d not in named)
        if unnamed:
            self.fail(name, f"carries {unnamed}, which the request does not name")
        payload = by_digest.get(request.get("payload_digest"))
        modes = {row["request"]: SUBMIT, **{n: (SUBMIT if n == payload else STORED)
                                            for n in carried}}
        if "refused" in row:
            stated: dict[str, list] = {}
            for refusal in row["refused"]:
                if refusal["record"] not in modes:
                    self.fail(name, f"refuses {refusal['record']}, which the step does not submit")
                stated.setdefault(refusal["record"], []).append(
                    {"code": refusal["code"], "pointer": refusal["pointer"]})
            for record, mode in modes.items():
                found = _violations(self.built[record], mode, self.schemas)
                key = sorted(json.dumps(v, sort_keys=True) for v in found)
                if key != sorted(json.dumps(v, sort_keys=True) for v in stated.get(record, [])):
                    self.fail(name, f"{record} is refused with {found}, "
                                    f"not {stated.get(record, [])}")
            return {"name": name, "request": row["request"], "carries": row["carries"],
                    "refused": row["refused"]}, []
        for record, mode in modes.items():
            found = _violations(self.built[record], mode, self.schemas)
            if found:
                self.fail(name, f"{record} is refused in {mode} mode: {found}")
        operation = request["operation"]
        takes, returns = table[operation]["takes"], table[operation]["returns"]
        if payload is None and takes:
            self.fail(name, f"{operation} takes {list(takes)}, and the request names no payload")
        if payload is not None and self.built[payload]["kind"] not in takes:
            self.fail(name, f"{operation} takes {list(takes)}, not {self.built[payload]['kind']}")
        answer = row["answer"]
        for returned in answer["returns"]:
            kind = self.record(returned).get("kind")
            if kind not in returns:
                self.fail(name, f"{operation} returns {list(returns)}, not {kind} ({returned})")
            found = _violations(self.built[returned], STORED, self.schemas)
            if found:
                self.fail(name, f"{returned} is not a record its owner could store: {found}")
        result_name = f"{name}_result"
        if result_name in self.specs:
            self.fail(name, f"{result_name} is the name of this step's generated result")
        self.uses[result_name] = set()
        outcome = {"stage": answer["stage"], "material_gaps": answer["gaps"]}
        if answer["stage"] == "committed":
            outcome["receipt_digest"] = self.value(f"$digest:{name}_receipt", result_name,
                                                   "/outcome/receipt_digest")
        result = {"kind": "operation_result", "schema": 1, "request_id": request["request_id"],
                  "request_digest": self.value(f"#{row['request']}", result_name,
                                               "/request_digest"),
                  "local_effect": answer["local_effect"],
                  "provider_effect": answer["provider_effect"], "outcome": outcome,
                  "outputs": [{"kind": self.built[r]["kind"],
                               "digest": self.value(f"#{r}", result_name, f"/outputs/{i}/digest")}
                              for i, r in enumerate(answer["returns"])],
                  "supported_recovery": answer["recovery"]}
        found = [{"code": v.code, "pointer": v.pointer}
                 for v in result_schema.validate(result, STORED)]
        if found:
            self.fail(name, f"no result the contract permits says this: {found}")
        self.built[result_name] = result
        self.digests[result_name] = canonical.digest_of(result)
        minted_here = set().union(self.uses[result_name],
                                  *(self.uses[r] for r in answer["returns"]))
        self.returned.update([result_name, *answer["returns"]])
        return ({"name": name, "request": row["request"], "carries": row["carries"],
                 "result": result_name, "returns": answer["returns"]}, sorted(minted_here))


def generate(spec_bytes: bytes, schemas: dict | None = None) -> dict:
    """The joined scenario a spec stands for, or ScenarioError naming why it cannot be one."""
    spec = canonical.parse(spec_bytes)
    shape = load_schema(canonical.parse(SCHEMA.read_bytes()))
    found = shape.validate(spec)
    if found:
        raise ScenarioError("; ".join(f"{v.code} at {v.pointer or '/'}" for v in found))
    schemas = schemas or examples.load_schemas()
    kinds = records.registry(schemas)
    result_schema = schemas[kinds["operation_result"][1]]
    table = operations()
    built = _Scenario(spec, schemas)
    steps, defined, definitions = [], set(), []
    names = [row["name"] for row in spec["steps"]]
    if len(set(names)) != len(names):
        built.fail("steps", "two steps share a name")
    for row in spec["steps"]:
        step, minted = built.step(row, table, defined, result_schema)
        steps.append(step)
        definitions.extend({"name": m, "shape": built.minted[m], "step": row["name"]}
                           for m in minted if m not in defined)
        defined.update(minted)
    unused = sorted(set(built.specs) - set(built.built))
    if unused:
        built.fail("records", f"{unused} are named by no step")
    return {"case": spec["case"], "says": spec["says"],
            "spec_sha256": hashlib.sha256(spec_bytes).hexdigest(),
            "ids": [{"name": n, "id": i} for n, i in built.ids.items()],
            "records": [{"name": n, "record": built.built[n], "digest": built.digests[n]}
                        for n in built.built],
            "steps": steps, "minted": definitions, "joins": built.joins}


def render(scenario: dict) -> bytes:
    return (json.dumps(scenario, indent=1, sort_keys=True, ensure_ascii=False) + "\n").encode()


def specs(directory: pathlib.Path = SCENARIOS) -> list[pathlib.Path]:
    return sorted(directory.glob(f"*/{SPEC}"))


def main(argv: list[str]) -> int:
    if argv not in ([], ["--check"]):
        print(__doc__.strip().splitlines()[-1], file=sys.stderr)
        return 2
    schemas = examples.load_schemas()
    problems = []
    for spec in specs():
        target = spec.with_name(GENERATED)
        try:
            rendered = render(generate(spec.read_bytes(), schemas))
        except ScenarioError as error:
            problems.append(str(error))
            continue
        if argv:
            if not target.is_file() or target.read_bytes() != rendered:
                problems.append(f"{target.relative_to(HERE)} differs from what its spec generates")
        else:
            target.write_bytes(rendered)
    for problem in problems:
        print(f"FAIL {problem}")
    count = len(specs())
    print(f"SCENARIOS {'OK' if not problems else 'FAIL'} ({count} specs, {len(problems)} problems)")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
