"""Scenarios: the joined bytes a case runs, generated from a short spec.

A case that drives an operation needs more than records that each pass their schema. The request
must name the digest of the payload beside it, the result must answer that request, and an id
must be the same one from step to step. Written by hand those joins drift, and two workers reading
one case fill them in differently. So a case's scenario is a spec (`spec.json`, shaped by
`scenario.schema.json`) and this module writes the joined bytes (`scenario.json`) beside it. The
spec, this module and the generated file together are the case's fixture.

Every record in a spec is a contract example with the leaves the case changes, so the examples
are the vocabulary and a spec states only differences. A record may instead derive from another
record of the same spec (`from` a bare name), which is how a second request repeats the first
with a new id and payload. A string value may name instead of state:

  "@name"          the id `name`: its prefix and 32 hex digits derived from the case and the name
  "#name"          the digest of the record `name` as this scenario builds it, or of the bytes
                   of the member `name`
  "$shape:name"    a value the owner mints — an id it assigns, a time, a count, the digest of
                   what it wrote. Its first place is in a record a step's answer returns. The
                   generated bytes carry a stand-in that satisfies the schema there (shape is an
                   id prefix, `digest`, `instant` or `integer`).

`members` states the bytes of source members a scenario names, and `#name` is their sha256. A
read that returns a member's body (an operation whose row returns `source_member`) names it among
the records its answer returns, so what the reader returns is those bytes, not only their digest.

`joins` in the generated file lists every place a name was resolved, so a driver can put the
owner's real value in each minted place, and recompute every digest over it and each size stated
beside one, before submitting.
A digest of a record a step returns is likewise the digest of what the owner actually returned.
Signing is the person's side, and the driver acts for the person: a key binding's public key and
a signature envelope's `sshsig` stand for what the driver's own key for that binding makes. The
driver holds one key per bound key and signs each envelope's `signed_digest` with it at run time,
so a signature verifies exactly when the bytes it names are the bytes it was made over.
A profile runs a case against the real files of its node and of the nodes its node depends on. A
step whose operation belongs to any other node (team.found in a case M1 runs, when M1 depends on
no Team node) is given: the driver answers it with the step's stated answer and places the
records it returns as given state, and a given step is never evidence about its own owner. The
profile a scenario runs on starts at the access generation its first request states: before the
first step the driver brings a new profile there through restrictions and re-entries of its own,
which are given. From there the generation moves only as the scenario's own steps move it.
A committed step's receipt is generated too, as the record `<step>_receipt` its result names:
the owner mints its sequence and time. Its head is the digest of the record the step stored
when the answer's `head` names one it returns (a collection's head is the collection record its
change stored), and otherwise a digest the owner mints under that name, which a later request's
base expects as `$digest:<head>`. A later operation.query can return the receipt by
that name, and a record the step's own answer returns may name it too. A step that `replays` an
earlier one resubmits the same request bytes and is answered with that step's result and receipt;
the owner writes nothing new. An answer under a new request id that the owner settles as a
duplicate states `receipt_of` the earlier committed step instead, and no receipt is written for it.

`world` is the harness around the steps, never a contract record: isolated processes, each step
naming the one it runs on; a controlled clock that each step may move forward, the generated step
stating the instant it runs at; partitions between two processes over a run of steps; and faults,
each killing the process of one answered step at a fault point B03 names and restarting it, so
that step's answer is what the owner returns for the same request after the restart — or, when
the fault names the step that `observed_by` it, what the owner committed, which the caller first
learns from that later query because no reply reached it. `during` runs one step while another is
in flight: after the owner admitted the other's request and before it answers. `events` are the
outside changes the harness makes between steps, each of a kind the spec's schema closes: a file
edited in the checkout a step reads, received package bytes that differ from what the inventory
advertises, a provider's token refresh arriving with no local transition, the key files arranged
beside or away from the agent or back as the runtime expects, a store setting, a build of the
checkout, an inventory of the checkout, the installed target or the knowledge package the product
ships, a provider's reply to a step that never arrives, and the repository identity a carrier
provider reports. A step may name the concrete `route` its request is submitted through, a row of
the entrance dispositions, with the root a caller chose instead of its own where that route takes
one. A runner step names a situation of the same case in the runner's preflight cases instead of a
request.

What can be decided from the spec alone is checked here and fails by name:
  - every record resolves, and every name it uses is defined;
  - an answered step's request and payload pass their schemas in submit mode, as does each
    record its `submits` names (a new policy a founding proposal names), and every other record
    it carries passes in stored mode; a refused step's records fail with exactly the refusals it
    states;
  - the digests a request names are exactly those of the records the step carries, apart from
    records an earlier step returned and values it minted; a carried record the request does not
    name must be named by its payload, or by a carried record so named (a batch's item requests
    and their payloads);
  - the payload is a kind its operation takes (no payload when it takes none), and every record
    the answer returns is a kind the operation returns;
  - every request states the effect class, grant action and kind of target its operation's row
    declares, the effect class aside when the answer is `effect_class_mismatch`;
  - the result built from the answer passes the result schema, so an answer the contract cannot
    give — a commit beside a gap that prevents one — cannot be written in a spec either;
  - a minted value is used only after the step whose answer first returns it;
  - the world's processes, partitions and faults name steps and processes that exist, a fault
    names a B03 fault point and an answered step, and a runner step a situation of its case;
  - a fault's observer is a later step that returns the faulted step's result; a step that runs
    during another is listed immediately before it, and the other's request uses nothing it mints;
  - an event names a step and records that exist, a file edit states bytes or absence and not
    both, an inventory yields a record or equals one an earlier inventory yielded, a lost reply
    names an answered step, and a route is a row of the entrance dispositions, overriding the
    root only where its disposition takes the root from the caller;
  - an answer's `receipt_of` names an earlier committed step, and such an answer states no head;
  - every member is named by a record or returned by a step, and a size stated beside the digest
    of a record or member of the scenario is that record's canonical size or the member's size;
  - a committed answer states the local effect `committed` (C03's meaning of the value).

  python3 gates/workenv/scenarios.py [CASE ...]           # write scenario.json from each spec
  python3 gates/workenv/scenarios.py --check [CASE ...]   # fail when one differs from its spec

A CASE is a case id or its directory name; none means every spec.
"""
from __future__ import annotations

import hashlib
import json
import pathlib
import re
import sys
from datetime import datetime, timedelta

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2]))
from workenv.contracts import b03, canonical, errors, examples, records  # noqa: E402
from workenv.contracts.c03 import EFFECT_CLASS_MISMATCH  # noqa: E402
from workenv.contracts.schema import STORED, SUBMIT, load_schema  # noqa: E402

HERE = pathlib.Path(__file__).resolve().parent
SCENARIOS = HERE / "fixtures" / "scenarios"
SCHEMA = HERE / "scenario.schema.json"
SPEC, GENERATED = "spec.json", "scenario.json"
PREFLIGHT = HERE / "fixtures" / "runner" / "preflight.json"
ENTRANCES = HERE / "entrances.jsonl"
# The event fields that name one of the spec's records, and the kind that record must be.
EVENT_RECORDS = {"provider_refresh": {"connection": "provider_connection"},
                 "key_layout": {"key": "principal_binding"},
                 "build": {"yields": "package_candidate"},
                 "inventory": {"yields": "source_manifest", "equals": "source_manifest"}}
STAND_IN_INSTANT = "2000-01-01T00:00:00Z"
INSTANT = "%Y-%m-%dT%H:%M:%SZ"
NAMED = re.compile(r"([@#])([a-z][a-z0-9]*(?:_[a-z0-9]+)*)\Z")
MINTED = re.compile(r"\$(digest|instant|integer|[a-z]{3}):([a-z][a-z0-9]*(?:_[a-z0-9]+)*)\Z")
# The request fields that name another record by digest.
NAMING = ("payload_digest", "recipient_digest", "policy_digests", "control_digests",
          "proof_digests")
DIGEST = re.compile(r"[0-9a-f]{64}\Z")


class ScenarioError(ValueError):
    """A spec this module cannot turn into joined bytes, named."""


def operations() -> dict[str, dict]:
    """operation -> its row (what it takes and returns, its effect class, the grant action it
    needs and the kinds of resource it targets), joined from the contract modules."""
    return {name: row for module in errors.OWNERS
            for name, row in getattr(module, "OPERATIONS", {}).items()}


def _digests_in(value) -> set[str]:
    if isinstance(value, dict):
        return set().union(*map(_digests_in, value.values()))
    if isinstance(value, list):
        return set().union(*map(_digests_in, value))
    return {value} if isinstance(value, str) and DIGEST.match(value) else set()


def _hex(*parts: str) -> str:
    return hashlib.sha256("/".join(parts).encode()).hexdigest()


def _segments(pointer: str) -> list[str]:
    return [part.replace("~1", "/").replace("~0", "~") for part in pointer.split("/")[1:]]


def _violations(value, mode: str, schemas: dict) -> list[dict]:
    """Refusals of one value read as a contract record, in the shape a spec states them."""
    try:
        identifier = records.resolve(value, records.registry(schemas))
    except records.RecordError as error:
        return [{"code": error.code, "pointer": error.pointer}]
    return [{"code": v.code, "pointer": v.pointer}
            for v in schemas[identifier].validate(value, mode)]


class _Scenario:
    def __init__(self, spec: dict, schemas: dict):
        self.case = spec["case"]
        self.schemas = schemas
        self.ids = {row["name"]: f"{row['prefix']}_{_hex(self.case, row['name'])[:32]}"
                    for row in spec["ids"]}
        self.specs = {row["name"]: row for row in spec["records"]}
        self.built: dict[str, object] = {}
        self.digests: dict[str, str] = {}
        self.uses: dict[str, set[str]] = {}      # record -> minted names it rests on
        self.minted: dict[str, str] = {}         # minted name -> shape
        self.joins: list[dict] = []
        self.open: list[str] = []
        self.returned: set[str] = set()          # records an earlier step's answer returned
        self.results: dict[str, dict] = {}       # answered step -> its request, result, returns
        self.members = {row["name"]: row["text"].encode("utf-8")
                        for row in spec.get("members", [])}  # member -> its bytes
        for name in self.members:
            if name in self.specs:
                self.fail(name, "names both a record and a member")
            self.uses[name] = set()
            self.digests[name] = hashlib.sha256(self.members[name]).hexdigest()
        preflight = canonical.parse(PREFLIGHT.read_bytes())
        self.situations = {s["name"] for row in preflight["cases"] if row["case"] == self.case
                           for s in row["situations"]}

    def fail(self, where: str, detail: str) -> None:
        raise ScenarioError(f"{self.case} {where}: {detail}")

    def stand_in(self, shape: str, name: str):
        if shape == "digest":
            return _hex(self.case, "minted", name)
        if shape == "instant":
            return STAND_IN_INSTANT
        if shape == "integer":
            return 1
        return f"{shape}_{_hex(self.case, 'minted', name)[:32]}"

    def value(self, raw, record: str, pointer: str):
        if isinstance(raw, list):
            return [self.value(item, record, f"{pointer}/{i}") for i, item in enumerate(raw)]
        if not isinstance(raw, str):
            return raw
        minted = MINTED.match(raw)
        if minted:
            shape, name = minted.groups()
            if self.minted.setdefault(name, shape) != shape:
                self.fail(f"{record}{pointer}",
                          f"${name} minted as {self.minted[name]} and {shape}")
            self.uses[record].add(name)
            self.joins.append({"record": record, "pointer": pointer, "minted": name})
            return self.stand_in(shape, name)
        named = NAMED.match(raw)
        if not named:
            return raw
        sigil, name = named.groups()
        if sigil == "@":
            if name not in self.ids:
                self.fail(f"{record}{pointer}", f"no id named {name!r}")
            return self.ids[name]
        digest = self.digest(name)
        self.uses[record] |= self.uses[name]
        self.joins.append({"record": record, "pointer": pointer, "digest_of": name})
        return digest

    def digest(self, name: str) -> str:
        if name not in self.members:
            self.record(name)
        return self.digests[name]

    def kind(self, name: str) -> str:
        return "source_member" if name in self.members else self.record(name).get("kind")

    def record(self, name: str):
        if name in self.built:
            return self.built[name]
        if name not in self.specs:
            self.fail(name, "no record by that name")
        if name in self.open:
            self.fail(name, f"names its own digest through {' -> '.join(self.open)}")
        self.open.append(name)
        row = self.specs[name]
        self.uses[name] = set()
        if "/" in row["from"]:
            path = examples.EXAMPLES / row["from"]
            if not path.is_file():
                self.fail(name, f"no example {row['from']}")
            value = canonical.parse(path.read_bytes())
        else:
            base = row["from"]
            value = json.loads(json.dumps(self.record(base)))
            self.uses[name] |= self.uses[base]
            self.joins.extend({**join, "record": name} for join in list(self.joins)
                              if join["record"] == base)
        for pointer in row.get("drop", []):
            parent, key = self.locate(value, pointer, name, create=False)
            del parent[key]
            self.unjoin(name, pointer)
        for change in row.get("set", []):
            parent, key = self.locate(value, change["pointer"], name, create=True)
            at = "/".join(change["pointer"].split("/")[:-1])
            self.unjoin(name, f"{at}/{key}")
            if isinstance(parent, list) and key == len(parent):
                parent.append(self.value(change["value"], name, f"{at}/{key}"))
            else:
                parent[key] = self.value(change["value"], name, f"{at}/{key}")
        self.open.pop()
        # What the record rests on is what its joins still name, not what it replaced.
        self.uses[name] = set().union(*({j["minted"]} if "minted" in j
                                        else self.uses[j["digest_of"]]
                                        for j in self.joins if j["record"] == name))
        try:
            self.digests[name] = canonical.digest_of(value)
        except canonical.CanonicalError as error:
            self.fail(name, f"is not a record canonical JSON can hold: {error}")
        self.built[name] = value
        return value

    def unjoin(self, name: str, pointer: str) -> None:
        """Forget what a derived record inherited at a place it now removes or replaces."""
        def under(join):
            return join["pointer"] == pointer or join["pointer"].startswith(f"{pointer}/")
        self.joins = [join for join in self.joins if join["record"] != name or not under(join)]

    def locate(self, document, pointer: str, name: str, create: bool):
        *path, last = _segments(pointer)
        node = document
        for at, part in enumerate(path):
            if isinstance(node, list):
                if create and part.isdigit() and int(part) == len(node):
                    node.append({})
                if not part.isdigit() or int(part) >= len(node):
                    self.fail(f"{name}{pointer}", f"no item {part}")
                node = node[int(part)]
            elif isinstance(node, dict):
                if part not in node:
                    if not create:
                        self.fail(f"{name}{pointer}", f"no field {part}")
                    # A missing field followed by index 0 or `-` is a new array.
                    node[part] = [] if (path + [last])[at + 1] in ("0", "-") else {}
                node = node[part]
            else:
                self.fail(f"{name}{pointer}", "passes through a value that is not a container")
        if isinstance(node, list):
            if last == "-" and create:
                return node, len(node)
            if not last.isdigit() or int(last) >= len(node):
                self.fail(f"{name}{pointer}", f"no item {last}")
            return node, int(last)
        if not isinstance(node, dict) or (not create and last not in node):
            self.fail(f"{name}{pointer}", f"no field {last}")
        return node, last

    def named_by(self, request: dict) -> list[str]:
        found = []
        for field in NAMING:
            value = request.get(field, [])
            found.extend(value if isinstance(value, list) else [value])
        return found

    def receipt(self, name: str, request_name: str, request: dict, head: str, step: str,
                stored: bool) -> None:
        """The receipt a committed step's owner writes, joined to its request and head: the
        digest of the record the step stored when it names one, or else a digest it mints."""
        self.uses[name] = set()
        receipt = {"kind": "operation_receipt", "schema": 1, "request_id": request["request_id"],
                   "request_digest": self.value(f"#{request_name}", name, "/request_digest"),
                   "owner": request["owner"], "target": request["target"],
                   "head_digest": self.value(f"#{head}" if stored else f"$digest:{head}", name,
                                             "/head_digest"),
                   "sequence": self.value(f"$integer:{step}_sequence", name, "/sequence"),
                   "committed_at": self.value(f"$instant:{step}_committed_at", name,
                                              "/committed_at")}
        # The owner and target are the request's, and so are the names resolved inside them.
        for join in [j for j in self.joins if j["record"] == request_name
                     and j["pointer"].startswith(("/owner/", "/target/"))]:
            self.joins.append({**join, "record": name})
            if "minted" in join:
                self.uses[name].add(join["minted"])
        found = _violations(receipt, STORED, self.schemas)
        if found:
            self.fail(step, f"no receipt the contract permits answers this request: {found}")
        self.built[name] = receipt
        self.digests[name] = canonical.digest_of(receipt)

    def convention(self, step: str, name: str, table: dict, gaps: list) -> None:
        """A request states its operation's effect class, grant action and kind of target."""
        request = self.built[name]
        row = table.get(request.get("operation"))
        if row is None:  # an operation no contract declares is refused by the request schema
            return
        stated = {"effect_class": request.get("effect_class"), "action": request.get("action")}
        wanted = {"effect_class": row["effect"], "action": row["action"]}
        if any(gap["code"] == EFFECT_CLASS_MISMATCH for gap in gaps):
            del stated["effect_class"], wanted["effect_class"]
        for field, value in wanted.items():
            if stated[field] != value:
                self.fail(step, f"{name} states {field} {stated[field]!r}; "
                                f"{request['operation']} is {value!r}")
        target = request.get("target", {}).get("resource_id", "")
        if target[:3] not in row["targets"]:
            self.fail(step, f"{name} targets {target[:3]}_; {request['operation']} targets "
                            f"{', '.join(row['targets'])}")

    def placed(self, row: dict) -> dict:
        """The step's name, and where and when it runs when the world says."""
        return {key: row[key] for key in ("name", "process", "at", "route") if key in row}

    def step(self, row: dict, table: dict, defined: set[str], result_schema) -> tuple[dict, list]:
        name = row["name"]
        if "runner" in row:
            if row["runner"] not in self.situations:
                self.fail(name, f"{self.case} has no runner situation {row['runner']!r}")
            return {**self.placed(row), "runner": row["runner"]}, []
        request = self.record(row["request"])
        carried = {n: self.record(n) for n in row["carries"]}
        if request.get("kind") != "operation_request":
            self.fail(name, f"{row['request']} is not an operation_request")
        early = set().union(*(self.uses[n] for n in [row["request"], *row["carries"]])) - defined
        if early:
            self.fail(name, f"uses {sorted(early)} before any step returns them")
        stand_ins = ({self.stand_in("digest", m) for m, shape in self.minted.items()
                      if shape == "digest" and m in defined}
                     | {self.digests[r] for r in self.returned})
        named = self.named_by(request)
        by_digest = {self.digests[n]: n for n in carried}
        loose = [d for d in named if d not in by_digest and d not in stand_ins]
        if loose:
            self.fail(name, f"the request names {loose}, which the step does not carry and no "
                            "earlier step returned or minted")
        payload = by_digest.get(request.get("payload_digest"))
        # What the payload names, and what a carried record it names names in turn: a batch's
        # plan names its item requests, and each item request names its own payload.
        inner, frontier, seen = set(), [payload] if payload else [], set()
        while frontier:
            record = frontier.pop()
            if record in seen:
                continue
            seen.add(record)
            found = _digests_in(self.built[record])
            inner |= found
            frontier.extend(by_digest[d] for d in found if d in by_digest)
        unnamed = sorted(n for n, d in ((n, self.digests[n]) for n in carried)
                         if d not in named and d not in inner)
        if unnamed:
            self.fail(name, f"carries {unnamed}, which the request does not name")
        submits = row.get("submits", [])
        for extra in submits:
            if extra not in carried or extra == payload:
                self.fail(name, f"submits {extra}, which is not a record it carries besides "
                                "its payload")
        modes = {row["request"]: SUBMIT, **{n: (SUBMIT if n == payload or n in submits
                                                else STORED) for n in carried}}
        gaps = row.get("answer", {}).get("gaps", [])
        for sent in [row["request"], *(n for n in carried
                                        if carried[n].get("kind") == "operation_request")]:
            self.convention(name, sent, table, gaps)
        if "refused" in row:
            stated: dict[str, list] = {}
            for refusal in row["refused"]:
                if refusal["record"] not in modes:
                    self.fail(name, f"refuses {refusal['record']}, which the step does not submit")
                stated.setdefault(refusal["record"], []).append(
                    {"code": refusal["code"], "pointer": refusal["pointer"]})
            for record, mode in modes.items():
                found = _violations(self.built[record], mode, self.schemas)
                key = sorted(json.dumps(v, sort_keys=True) for v in found)
                if key != sorted(json.dumps(v, sort_keys=True) for v in stated.get(record, [])):
                    self.fail(name, f"{record} is refused with {found}, "
                                    f"not {stated.get(record, [])}")
            return {**self.placed(row), "request": row["request"], "carries": row["carries"],
                    **({"submits": submits} if submits else {}), "refused": row["refused"]}, []
        for record, mode in modes.items():
            found = _violations(self.built[record], mode, self.schemas)
            if found:
                self.fail(name, f"{record} is refused in {mode} mode: {found}")
        if "replays" in row:
            earlier = self.results.get(row["replays"])
            if earlier is None:
                self.fail(name, f"replays {row['replays']}, which is no earlier answered step")
            if self.digests[earlier["request"]] != self.digests[row["request"]]:
                self.fail(name, f"replays {row['replays']} with other request bytes")
            return ({**self.placed(row), "request": row["request"], "carries": row["carries"],
                     **({"submits": submits} if submits else {}), "replays": row["replays"],
                     "result": earlier["result"], "returns": earlier["returns"]}, [])
        operation = request["operation"]
        takes, returns = table[operation]["takes"], table[operation]["returns"]
        if payload is None and takes:
            self.fail(name, f"{operation} takes {list(takes)}, and the request names no payload")
        if payload is not None and self.built[payload]["kind"] not in takes:
            self.fail(name, f"{operation} takes {list(takes)}, not {self.built[payload]['kind']}")
        answer = row["answer"]
        head, reused = answer.get("head"), answer.get("receipt_of")
        if (head is not None or reused is not None) and answer["stage"] != "committed":
            self.fail(name, "names a head or a receipt, and only a committed answer has one")
        if head is not None and reused is not None:
            self.fail(name, "names an earlier receipt, and a new head only a new receipt states")
        if answer["stage"] == "committed" and answer["local_effect"] != "committed":
            self.fail(name, f"a committed answer states local_effect 'committed', not "
                            f"{answer['local_effect']!r}")
        if head in self.specs and head not in answer["returns"]:
            self.fail(name, f"names the record {head} as its head, and the answer does not "
                            "return it")
        result_name, receipt_name = f"{name}_result", f"{name}_receipt"
        for generated in (result_name, receipt_name):
            if generated in self.specs:
                self.fail(name, f"{generated} is the name of a record this step generates")
        # The receipt comes first, so a record the answer returns can name its own step's receipt.
        receipts = []
        if reused is not None:
            if f"{reused}_receipt" not in self.built or reused not in self.results:
                self.fail(name, f"answers with the receipt of {reused}, which no earlier "
                                "committed step wrote")
            receipt_name = f"{reused}_receipt"
        elif answer["stage"] == "committed":
            self.receipt(receipt_name, row["request"], request, head or f"{name}_head", name,
                         stored=head in answer["returns"])
            receipts = [receipt_name]
        for returned in answer["returns"]:
            kind = self.kind(returned)
            if kind not in returns:
                self.fail(name, f"{operation} returns {list(returns)}, not {kind} ({returned})")
            if returned in self.members:
                continue
            found = _violations(self.built[returned], STORED, self.schemas)
            if found:
                self.fail(name, f"{returned} is not a record its owner could store: {found}")
        self.uses[result_name] = set()
        outcome = {"stage": answer["stage"], "material_gaps": answer["gaps"]}
        if answer["stage"] == "committed":
            outcome["receipt_digest"] = self.value(f"#{receipt_name}", result_name,
                                                   "/outcome/receipt_digest")
        result = {"kind": "operation_result", "schema": 1, "request_id": request["request_id"],
                  "request_digest": self.value(f"#{row['request']}", result_name,
                                               "/request_digest"),
                  "local_effect": answer["local_effect"],
                  "provider_effect": answer["provider_effect"], "outcome": outcome,
                  "outputs": [{"kind": self.kind(r),
                               "digest": self.value(f"#{r}", result_name, f"/outputs/{i}/digest")}
                              for i, r in enumerate(answer["returns"])],
                  "supported_recovery": answer["recovery"]}
        found = [{"code": v.code, "pointer": v.pointer}
                 for v in result_schema.validate(result, STORED)]
        if found:
            self.fail(name, f"no result the contract permits says this: {found}")
        self.built[result_name] = result
        self.digests[result_name] = canonical.digest_of(result)
        minted_here = set().union(self.uses[result_name],
                                  *(self.uses[r] for r in [*receipts, *answer["returns"]]))
        self.returned.update([result_name, *receipts, *answer["returns"]])
        self.results[name] = {"request": row["request"], "result": result_name,
                              "returns": answer["returns"]}
        return ({**self.placed(row), "request": row["request"], "carries": row["carries"],
                 **({"submits": submits} if submits else {}),
                 "result": result_name, "returns": answer["returns"],
                 **({"head": head} if head else {}),
                 **({"receipt_of": reused} if reused else {})}, sorted(minted_here))


def generate(spec_bytes: bytes, schemas: dict | None = None) -> dict:
    """The joined scenario a spec stands for, or ScenarioError naming why it cannot be one."""
    spec = canonical.parse(spec_bytes)
    shape = load_schema(canonical.parse(SCHEMA.read_bytes()))
    found = shape.validate(spec)
    if found:
        raise ScenarioError("; ".join(f"{v.code} at {v.pointer or '/'}" for v in found))
    schemas = schemas or examples.load_schemas()
    kinds = records.registry(schemas)
    result_schema = schemas[kinds["operation_result"][1]]
    table = operations()
    built = _Scenario(spec, schemas)
    steps, defined, definitions = [], set(), []
    names = [row["name"] for row in spec["steps"]]
    if len(set(names)) != len(names):
        built.fail("steps", "two steps share a name")
    world = spec.get("world", {})
    placed(built, world, spec["steps"], names)
    during = {pair["step"]: pair["runs"] for pair in world.get("during", [])}
    minted_by: dict[str, set[str]] = {}
    for row in spec["steps"]:
        step, minted = built.step(row, table, defined, result_schema)
        minted_by[row["name"]] = set(minted) - defined
        if row["name"] in during:
            # Its request was sent before the step running during it started.
            sent = set().union(*(built.uses[n] for n in [row["request"], *row["carries"]]))
            early = sorted(sent & minted_by[during[row["name"]]])
            if early:
                built.fail(row["name"], f"its request was sent before {during[row['name']]} ran, "
                                        f"and uses {early}, which that step mints")
        steps.append(step)
        definitions.extend({"name": m, "shape": built.minted[m], "step": row["name"]}
                           for m in minted if m not in defined)
        defined.update(minted)
    for event in world.get("events", []):
        for field, kind in EVENT_RECORDS.get(event["kind"], {}).items():
            if field in event:
                if event[field] not in built.specs:
                    built.fail("world", f"a {event['kind']} event names {event[field]}, which is "
                                        "no record")
                if built.record(event[field]).get("kind") != kind:
                    built.fail("world", f"a {event['kind']} event names {event[field]}, which is "
                                        f"no {kind}")
    unused = sorted(set(built.specs) - set(built.built))
    if unused:
        built.fail("records", f"{unused} are named by no step")
    named = {join.get("digest_of") for join in built.joins} | set().union(
        *(set(row["returns"]) for row in built.results.values()))
    idle = sorted(set(built.members) - named)
    if idle:
        built.fail("members", f"{idle} are named by no record and returned by no step")
    sized(built)
    return {"case": spec["case"], "says": spec["says"],
            **({"world": stated(world)} if world else {}),
            "spec_sha256": hashlib.sha256(spec_bytes).hexdigest(),
            "ids": [{"name": n, "id": i} for n, i in built.ids.items()],
            "records": [{"name": n, "record": built.built[n], "digest": built.digests[n]}
                        for n in built.built],
            **({"members": [{"name": n, "text": data.decode("utf-8"), "digest": built.digests[n],
                             "size": len(data)} for n, data in built.members.items()]}
               if built.members else {}),
            "steps": steps, "minted": definitions, "joins": built.joins}


def sized(built: _Scenario) -> None:
    """Hold every stated size beside a joined digest to the bytes that digest is of."""
    sizes = {built.digests[n]: len(canonical.encode(v)) for n, v in built.built.items()}
    sizes.update({built.digests[n]: len(data) for n, data in built.members.items()})

    def walk(value, record: str, pointer: str) -> None:
        if isinstance(value, dict):
            size = sizes.get(value.get("digest"))
            if size is not None and isinstance(value.get("size"), int) and value["size"] != size:
                built.fail(record, f"{pointer or '/'} states size {value['size']} beside a digest "
                                   f"of {size} bytes")
            for key, item in value.items():
                walk(item, record, f"{pointer}/{key}")
        elif isinstance(value, list):
            for i, item in enumerate(value):
                walk(item, record, f"{pointer}/{i}")

    for name, value in built.built.items():
        walk(value, name, "")


def placed(built: _Scenario, world: dict, steps: list[dict], names: list[str]) -> None:
    """Hold the world to the steps, and state on each step where and when it runs."""
    processes = world.get("processes", [])
    clock = world.get("clock")
    if clock:
        now = datetime.strptime(clock["start"], INSTANT)
    for row in steps:
        if "runner" in row:
            continue
        if processes and row.get("process") not in processes:
            built.fail(row["name"], f"runs on no process of {processes}")
        if not processes and "process" in row:
            built.fail(row["name"], "names a process, and the world declares none")
        if "advance_seconds" in row and not clock:
            built.fail(row["name"], "moves a clock the world does not declare")
        if clock:
            now += timedelta(seconds=row.get("advance_seconds", 0))
            row["at"] = now.strftime(INSTANT)
    for partition in world.get("partitions", []):
        for process in partition["between"]:
            if process not in processes:
                built.fail("world", f"partitions {process}, which is no process")
        ends = [partition["from"], *([partition["until"]] if "until" in partition else [])]
        for end in ends:
            if end not in names:
                built.fail("world", f"partitions from or until {end}, which is no step")
        if len(ends) == 2 and names.index(ends[0]) >= names.index(ends[1]):
            built.fail("world", f"a partition ends at {ends[1]} before it starts")
    answered = {row["name"]: row for row in steps if "answer" in row}
    faulted = [fault["step"] for fault in world.get("faults", [])]
    for fault in world.get("faults", []):
        if fault["step"] not in answered:
            built.fail("world", f"faults {fault['step']}, which is no answered step")
        if fault["point"] not in b03.FAULT_POINTS:
            built.fail("world", f"{fault['point']} is no fault point B03 declares")
        seen = fault.get("observed_by")
        if seen is not None and (seen not in answered or names.index(seen) <= names.index(
                fault["step"]) or f"{fault['step']}_result" not in answered[seen]["answer"][
                "returns"]):
            built.fail("world", f"{fault['step']} is observed by {seen}, which is no later "
                                f"answered step returning {fault['step']}_result")
    if len(set(faulted)) != len(faulted):
        built.fail("world", "two faults kill one step")
    inner = [pair["runs"] for pair in world.get("during", [])]
    for pair in world.get("during", []):
        if pair["step"] not in answered or pair["runs"] not in answered:
            built.fail("world", f"{pair['runs']} runs during {pair['step']}, and both must be "
                                "answered steps")
        if names.index(pair["runs"]) + 1 != names.index(pair["step"]):
            built.fail("world", f"{pair['runs']} runs during {pair['step']}, and must be listed "
                                "immediately before it")
    if len(set(inner)) != len(inner) or set(inner) & {p["step"] for p in world.get("during", [])}:
        built.fail("world", "a step runs during two steps, or both runs during one and has one "
                            "run during it")
    inventoried: set[str] = set()
    for event in sorted(world.get("events", []),
                        key=lambda e: names.index(e["before"]) if e.get("before") in names else -1):
        kind = event["kind"]
        if kind == "reply_lost":
            if event["step"] not in answered:
                built.fail("world", f"a reply is lost from {event['step']}, which is no answered "
                                    "step")
            continue
        if event["before"] not in names:
            built.fail("world", f"a {kind} event comes before {event['before']}, which is no step")
        if "process" in event and event["process"] not in processes:
            built.fail("world", f"a {kind} event runs on {event['process']}, which is no process")
        if kind == "file_edit" and ("bytes" in event) == ("absent" in event):
            built.fail("world", f"the file edit of {event['path']} states bytes or absence, not "
                                "both or neither")
        if kind == "inventory":
            if ("yields" in event) == ("equals" in event):
                built.fail("world", "an inventory yields a record or equals an earlier one, not "
                                    "both or neither")
            if "equals" in event and event["equals"] not in inventoried:
                built.fail("world", f"an inventory equals {event['equals']}, which no earlier "
                                    "inventory yielded")
            inventoried.update([event["yields"]] if "yields" in event else [])
    routes = {(row["route"]["path"], row["route"].get("command")): row["disposition"]
              for row in map(json.loads, ENTRANCES.read_text(encoding="utf-8").splitlines())}
    for row in (row for row in steps if "route" in row):
        route = row["route"]
        disposition = routes.get((route["path"], route.get("command")))
        if disposition is None:
            built.fail(row["name"], f"is submitted through {route}, which is no entrance "
                                    "disposition")
        if "root_override" in route and disposition.get("root_origin") != "caller":
            built.fail(row["name"], f"overrides the root of {route['path']}, whose disposition "
                                    "does not take its root from the caller")


def stated(world: dict) -> dict:
    """The world as generated: each event that writes bytes states their digest and size."""
    world = json.loads(json.dumps(world))
    for event in world.get("events", []):
        if "bytes" in event:
            data = event["bytes"].encode("utf-8")
            event.update(digest=hashlib.sha256(data).hexdigest(), size=len(data))
    return world


def render(scenario: dict) -> bytes:
    return (json.dumps(scenario, indent=1, sort_keys=True, ensure_ascii=False) + "\n").encode()


def specs(directory: pathlib.Path = SCENARIOS, only: list[str] | None = None) -> list[pathlib.Path]:
    found = sorted(directory.glob(f"*/{SPEC}"))
    if only is None:
        return found
    wanted = {name.lower() for name in only}
    return [spec for spec in found if spec.parent.name in wanted]


def main(argv: list[str]) -> int:
    check = argv[:1] == ["--check"]
    only = argv[1:] if check else argv
    if any(name.startswith("-") for name in only):
        print(__doc__.strip().splitlines()[-3], file=sys.stderr)
        return 2
    chosen = specs(only=only or None)
    if only and len(chosen) != len({name.lower() for name in only}):
        print(f"FAIL no spec for some of {only}")
        return 1
    schemas = examples.load_schemas()
    problems = []
    for spec in chosen:
        target = spec.with_name(GENERATED)
        try:
            rendered = render(generate(spec.read_bytes(), schemas))
        except ScenarioError as error:
            problems.append(str(error))
            continue
        if check:
            if not target.is_file() or target.read_bytes() != rendered:
                problems.append(f"{target.relative_to(HERE)} differs from what its spec generates")
        else:
            target.write_bytes(rendered)
    for problem in problems:
        print(f"FAIL {problem}")
    print(f"SCENARIOS {'OK' if not problems else 'FAIL'} ({len(chosen)} specs, "
          f"{len(problems)} problems)")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
